//Generated by script in project CodeGenerator
//Copyright Dawid Dyrcz 2020 see license file

namespace Dynamic.Tekla.Structures.Model.Collaboration
{

    public sealed class IFC2X3_ParametricObject_LShapeProfile 
    {

		public System.Double Depth
		{
			get => ifc2x3_parametricobject_lshapeprofile.Depth;
			set { ifc2x3_parametricobject_lshapeprofile.Depth = value; }
		}

		public System.Double Width
		{
			get => ifc2x3_parametricobject_lshapeprofile.Width;
			set { ifc2x3_parametricobject_lshapeprofile.Width = value; }
		}

		public System.Double Thickness
		{
			get => ifc2x3_parametricobject_lshapeprofile.Thickness;
			set { ifc2x3_parametricobject_lshapeprofile.Thickness = value; }
		}

		public System.Double FilletRadius
		{
			get => ifc2x3_parametricobject_lshapeprofile.FilletRadius;
			set { ifc2x3_parametricobject_lshapeprofile.FilletRadius = value; }
		}

		public System.Double EdgeRadius
		{
			get => ifc2x3_parametricobject_lshapeprofile.EdgeRadius;
			set { ifc2x3_parametricobject_lshapeprofile.EdgeRadius = value; }
		}

		public System.Double LegSlope
		{
			get => ifc2x3_parametricobject_lshapeprofile.LegSlope;
			set { ifc2x3_parametricobject_lshapeprofile.LegSlope = value; }
		}

		public Dynamic.Tekla.Structures.Geometry3d.Point Origin
		{
			get => Dynamic.Tekla.Structures.Geometry3d.Point_.FromTSObject(ifc2x3_parametricobject_lshapeprofile.Origin);
			set { ifc2x3_parametricobject_lshapeprofile.Origin = Dynamic.Tekla.Structures.Geometry3d.Point_.GetTSObject(value); }
		}

		public Dynamic.Tekla.Structures.Geometry3d.Vector xDir
		{
			get => Dynamic.Tekla.Structures.Geometry3d.Vector_.FromTSObject(ifc2x3_parametricobject_lshapeprofile.xDir);
			set { ifc2x3_parametricobject_lshapeprofile.xDir = Dynamic.Tekla.Structures.Geometry3d.Vector_.GetTSObject(value); }
		}

		public Dynamic.Tekla.Structures.Geometry3d.Vector Extrusion
		{
			get => Dynamic.Tekla.Structures.Geometry3d.Vector_.FromTSObject(ifc2x3_parametricobject_lshapeprofile.Extrusion);
			set { ifc2x3_parametricobject_lshapeprofile.Extrusion = Dynamic.Tekla.Structures.Geometry3d.Vector_.GetTSObject(value); }
		}

		public System.String ProfileName
		{
			get => ifc2x3_parametricobject_lshapeprofile.ProfileName;
			set { ifc2x3_parametricobject_lshapeprofile.ProfileName = value; }
		}

		public System.String Name
		{
			get => ifc2x3_parametricobject_lshapeprofile.Name;
			set { ifc2x3_parametricobject_lshapeprofile.Name = value; }
		}

		public System.String Description
		{
			get => ifc2x3_parametricobject_lshapeprofile.Description;
			set { ifc2x3_parametricobject_lshapeprofile.Description = value; }
		}

		public System.String ObjectType
		{
			get => ifc2x3_parametricobject_lshapeprofile.ObjectType;
			set { ifc2x3_parametricobject_lshapeprofile.ObjectType = value; }
		}

        

        internal dynamic ifc2x3_parametricobject_lshapeprofile;
        
        public IFC2X3_ParametricObject_LShapeProfile()
        {
            this.ifc2x3_parametricobject_lshapeprofile =  TSActivator.CreateInstance("Tekla.Structures.Model.Collaboration.IFC2X3_ParametricObject_LShapeProfile");
        }

        internal IFC2X3_ParametricObject_LShapeProfile(dynamic tsObject)
        {
            this.ifc2x3_parametricobject_lshapeprofile = tsObject;
        }





    }

    internal static class IFC2X3_ParametricObject_LShapeProfile_
    {
        public static dynamic GetTSObject(IFC2X3_ParametricObject_LShapeProfile dynObject)
        {
            return dynObject.ifc2x3_parametricobject_lshapeprofile;
        }

        public static IFC2X3_ParametricObject_LShapeProfile FromTSObject(dynamic tsObject)
        {
            return new IFC2X3_ParametricObject_LShapeProfile(tsObject);
        }
    }


}
    
