//Generated by script in project CodeGenerator
//Copyright Dawid Dyrcz 2020 see license file

namespace Dynamic.Tekla.Structures.Model.Collaboration
{

    public sealed class IFC2X3_ParametricObject_TShapeProfile 
    {

		public System.Double Depth
		{
			get => ifc2x3_parametricobject_tshapeprofile.Depth;
			set { ifc2x3_parametricobject_tshapeprofile.Depth = value; }
		}

		public System.Double FlangeWidth
		{
			get => ifc2x3_parametricobject_tshapeprofile.FlangeWidth;
			set { ifc2x3_parametricobject_tshapeprofile.FlangeWidth = value; }
		}

		public System.Double WebThickness
		{
			get => ifc2x3_parametricobject_tshapeprofile.WebThickness;
			set { ifc2x3_parametricobject_tshapeprofile.WebThickness = value; }
		}

		public System.Double FlangeThickness
		{
			get => ifc2x3_parametricobject_tshapeprofile.FlangeThickness;
			set { ifc2x3_parametricobject_tshapeprofile.FlangeThickness = value; }
		}

		public System.Double FilletRadius
		{
			get => ifc2x3_parametricobject_tshapeprofile.FilletRadius;
			set { ifc2x3_parametricobject_tshapeprofile.FilletRadius = value; }
		}

		public System.Double FlangeEdgeRadius
		{
			get => ifc2x3_parametricobject_tshapeprofile.FlangeEdgeRadius;
			set { ifc2x3_parametricobject_tshapeprofile.FlangeEdgeRadius = value; }
		}

		public System.Double WebEdgeRadius
		{
			get => ifc2x3_parametricobject_tshapeprofile.WebEdgeRadius;
			set { ifc2x3_parametricobject_tshapeprofile.WebEdgeRadius = value; }
		}

		public System.Double WebSlope
		{
			get => ifc2x3_parametricobject_tshapeprofile.WebSlope;
			set { ifc2x3_parametricobject_tshapeprofile.WebSlope = value; }
		}

		public System.Double FlangeSlope
		{
			get => ifc2x3_parametricobject_tshapeprofile.FlangeSlope;
			set { ifc2x3_parametricobject_tshapeprofile.FlangeSlope = value; }
		}

		public Dynamic.Tekla.Structures.Geometry3d.Point Origin
		{
			get => Dynamic.Tekla.Structures.Geometry3d.Point_.FromTSObject(ifc2x3_parametricobject_tshapeprofile.Origin);
			set { ifc2x3_parametricobject_tshapeprofile.Origin = Dynamic.Tekla.Structures.Geometry3d.Point_.GetTSObject(value); }
		}

		public Dynamic.Tekla.Structures.Geometry3d.Vector xDir
		{
			get => Dynamic.Tekla.Structures.Geometry3d.Vector_.FromTSObject(ifc2x3_parametricobject_tshapeprofile.xDir);
			set { ifc2x3_parametricobject_tshapeprofile.xDir = Dynamic.Tekla.Structures.Geometry3d.Vector_.GetTSObject(value); }
		}

		public Dynamic.Tekla.Structures.Geometry3d.Vector Extrusion
		{
			get => Dynamic.Tekla.Structures.Geometry3d.Vector_.FromTSObject(ifc2x3_parametricobject_tshapeprofile.Extrusion);
			set { ifc2x3_parametricobject_tshapeprofile.Extrusion = Dynamic.Tekla.Structures.Geometry3d.Vector_.GetTSObject(value); }
		}

		public System.String ProfileName
		{
			get => ifc2x3_parametricobject_tshapeprofile.ProfileName;
			set { ifc2x3_parametricobject_tshapeprofile.ProfileName = value; }
		}

		public System.String Name
		{
			get => ifc2x3_parametricobject_tshapeprofile.Name;
			set { ifc2x3_parametricobject_tshapeprofile.Name = value; }
		}

		public System.String Description
		{
			get => ifc2x3_parametricobject_tshapeprofile.Description;
			set { ifc2x3_parametricobject_tshapeprofile.Description = value; }
		}

		public System.String ObjectType
		{
			get => ifc2x3_parametricobject_tshapeprofile.ObjectType;
			set { ifc2x3_parametricobject_tshapeprofile.ObjectType = value; }
		}

        

        internal dynamic ifc2x3_parametricobject_tshapeprofile;
        
        public IFC2X3_ParametricObject_TShapeProfile()
        {
            this.ifc2x3_parametricobject_tshapeprofile =  TSActivator.CreateInstance("Tekla.Structures.Model.Collaboration.IFC2X3_ParametricObject_TShapeProfile");
        }

        internal IFC2X3_ParametricObject_TShapeProfile(dynamic tsObject)
        {
            this.ifc2x3_parametricobject_tshapeprofile = tsObject;
        }





    }

    internal static class IFC2X3_ParametricObject_TShapeProfile_
    {
        public static dynamic GetTSObject(IFC2X3_ParametricObject_TShapeProfile dynObject)
        {
            return dynObject.ifc2x3_parametricobject_tshapeprofile;
        }

        public static IFC2X3_ParametricObject_TShapeProfile FromTSObject(dynamic tsObject)
        {
            return new IFC2X3_ParametricObject_TShapeProfile(tsObject);
        }
    }


}
    
