//Generated by script in project CodeGenerator
//Copyright Dawid Dyrcz 2020 see license file

namespace Dynamic.Tekla.Structures.Model.Collaboration
{

    public  class IFC2X3_ParametricObject_RectangleHollowProfile  : Dynamic.Tekla.Structures.Model.Collaboration.ReferenceModelObjectAttribute
    {

		public System.Double XDim
		{
			get => teklaObject.XDim;
			set { teklaObject.XDim = value; }
		}

		public System.Double YDim
		{
			get => teklaObject.YDim;
			set { teklaObject.YDim = value; }
		}

		public System.Double WallThickness
		{
			get => teklaObject.WallThickness;
			set { teklaObject.WallThickness = value; }
		}

		public System.Double InnerFilletRadius
		{
			get => teklaObject.InnerFilletRadius;
			set { teklaObject.InnerFilletRadius = value; }
		}

		public System.Double OuterFilletRadius
		{
			get => teklaObject.OuterFilletRadius;
			set { teklaObject.OuterFilletRadius = value; }
		}

		public Dynamic.Tekla.Structures.Geometry3d.Point Origin
		{
			get => Dynamic.Tekla.Structures.Geometry3d.Point_.FromTSObject(teklaObject.Origin);
			set { teklaObject.Origin = Dynamic.Tekla.Structures.Geometry3d.Point_.GetTSObject(value); }
		}

		public Dynamic.Tekla.Structures.Geometry3d.Vector xDir
		{
			get => Dynamic.Tekla.Structures.Geometry3d.Vector_.FromTSObject(teklaObject.xDir);
			set { teklaObject.xDir = Dynamic.Tekla.Structures.Geometry3d.Vector_.GetTSObject(value); }
		}

		public Dynamic.Tekla.Structures.Geometry3d.Vector Extrusion
		{
			get => Dynamic.Tekla.Structures.Geometry3d.Vector_.FromTSObject(teklaObject.Extrusion);
			set { teklaObject.Extrusion = Dynamic.Tekla.Structures.Geometry3d.Vector_.GetTSObject(value); }
		}

		public System.String ProfileName
		{
			get => teklaObject.ProfileName;
			set { teklaObject.ProfileName = value; }
		}

		public System.String Name
		{
			get => teklaObject.Name;
			set { teklaObject.Name = value; }
		}

		public System.String Description
		{
			get => teklaObject.Description;
			set { teklaObject.Description = value; }
		}

		public System.String ObjectType
		{
			get => teklaObject.ObjectType;
			set { teklaObject.ObjectType = value; }
		}

        

        internal dynamic teklaObject;

		internal IFC2X3_ParametricObject_RectangleHollowProfile() {}





    }

    internal static class IFC2X3_ParametricObject_RectangleHollowProfile_
    {
        public static dynamic GetTSObject(IFC2X3_ParametricObject_RectangleHollowProfile dynObject)
        {
            return dynObject.teklaObject;
        }

        public static IFC2X3_ParametricObject_RectangleHollowProfile FromTSObject(dynamic tsObject)
        {
            return new IFC2X3_ParametricObject_RectangleHollowProfile() { teklaObject = tsObject };
        }
    }


}
    
