//Generated by script in project CodeGenerator
//Copyright Dawid Dyrcz 2020 see license file

namespace Dynamic.Tekla.Structures.Model.Collaboration
{

    public sealed class IFC2X3_ParametricObject_ZShapeProfile 
    {

		public System.Double Depth
		{
			get => ifc2x3_parametricobject_zshapeprofile.Depth;
			set { ifc2x3_parametricobject_zshapeprofile.Depth = value; }
		}

		public System.Double FlangeWidth
		{
			get => ifc2x3_parametricobject_zshapeprofile.FlangeWidth;
			set { ifc2x3_parametricobject_zshapeprofile.FlangeWidth = value; }
		}

		public System.Double WebThickness
		{
			get => ifc2x3_parametricobject_zshapeprofile.WebThickness;
			set { ifc2x3_parametricobject_zshapeprofile.WebThickness = value; }
		}

		public System.Double FlangeThickness
		{
			get => ifc2x3_parametricobject_zshapeprofile.FlangeThickness;
			set { ifc2x3_parametricobject_zshapeprofile.FlangeThickness = value; }
		}

		public System.Double FilletRadius
		{
			get => ifc2x3_parametricobject_zshapeprofile.FilletRadius;
			set { ifc2x3_parametricobject_zshapeprofile.FilletRadius = value; }
		}

		public System.Double EdgeRadius
		{
			get => ifc2x3_parametricobject_zshapeprofile.EdgeRadius;
			set { ifc2x3_parametricobject_zshapeprofile.EdgeRadius = value; }
		}

		public Dynamic.Tekla.Structures.Geometry3d.Point Origin
		{
			get => new Dynamic.Tekla.Structures.Geometry3d.Point(ifc2x3_parametricobject_zshapeprofile.Origin);
			set { ifc2x3_parametricobject_zshapeprofile.Origin = value.GetTSObject(); }
		}

		public Dynamic.Tekla.Structures.Geometry3d.Vector xDir
		{
			get => new Dynamic.Tekla.Structures.Geometry3d.Vector(ifc2x3_parametricobject_zshapeprofile.xDir);
			set { ifc2x3_parametricobject_zshapeprofile.xDir = value.GetTSObject(); }
		}

		public Dynamic.Tekla.Structures.Geometry3d.Vector Extrusion
		{
			get => new Dynamic.Tekla.Structures.Geometry3d.Vector(ifc2x3_parametricobject_zshapeprofile.Extrusion);
			set { ifc2x3_parametricobject_zshapeprofile.Extrusion = value.GetTSObject(); }
		}

		public System.String ProfileName
		{
			get => ifc2x3_parametricobject_zshapeprofile.ProfileName;
			set { ifc2x3_parametricobject_zshapeprofile.ProfileName = value; }
		}

		public System.String Name
		{
			get => ifc2x3_parametricobject_zshapeprofile.Name;
			set { ifc2x3_parametricobject_zshapeprofile.Name = value; }
		}

		public System.String Description
		{
			get => ifc2x3_parametricobject_zshapeprofile.Description;
			set { ifc2x3_parametricobject_zshapeprofile.Description = value; }
		}

		public System.String ObjectType
		{
			get => ifc2x3_parametricobject_zshapeprofile.ObjectType;
			set { ifc2x3_parametricobject_zshapeprofile.ObjectType = value; }
		}

        

        dynamic ifc2x3_parametricobject_zshapeprofile;
        
        public IFC2X3_ParametricObject_ZShapeProfile()
        {
            this.ifc2x3_parametricobject_zshapeprofile =  TSActivator.CreateInstance("Tekla.Structures.Model.Collaboration.IFC2X3_ParametricObject_ZShapeProfile");
        }

        public IFC2X3_ParametricObject_ZShapeProfile(dynamic tsObject)
        {
            this.ifc2x3_parametricobject_zshapeprofile = tsObject;
			this.Depth = ifc2x3_parametricobject_zshapeprofile.Depth;
			this.FlangeWidth = ifc2x3_parametricobject_zshapeprofile.FlangeWidth;
			this.WebThickness = ifc2x3_parametricobject_zshapeprofile.WebThickness;
			this.FlangeThickness = ifc2x3_parametricobject_zshapeprofile.FlangeThickness;
			this.FilletRadius = ifc2x3_parametricobject_zshapeprofile.FilletRadius;
			this.EdgeRadius = ifc2x3_parametricobject_zshapeprofile.EdgeRadius;
			this.Origin = new Dynamic.Tekla.Structures.Geometry3d.Point(ifc2x3_parametricobject_zshapeprofile.Origin);
			this.xDir = new Dynamic.Tekla.Structures.Geometry3d.Vector(ifc2x3_parametricobject_zshapeprofile.xDir);
			this.Extrusion = new Dynamic.Tekla.Structures.Geometry3d.Vector(ifc2x3_parametricobject_zshapeprofile.Extrusion);
			this.ProfileName = ifc2x3_parametricobject_zshapeprofile.ProfileName;
			this.Name = ifc2x3_parametricobject_zshapeprofile.Name;
			this.Description = ifc2x3_parametricobject_zshapeprofile.Description;
			this.ObjectType = ifc2x3_parametricobject_zshapeprofile.ObjectType;

        }


        public dynamic GetTSObject() => ifc2x3_parametricobject_zshapeprofile;





    }

}
    
