//Generated by script in project CodeGenerator
//Copyright Dawid Dyrcz 2020 see license file

namespace Dynamic.Tekla.Structures.Model
{

    public  class BoltArray  : Dynamic.Tekla.Structures.Model.BoltGroup
    {

        

        

		public BoltArray()
		{
			this.teklaObject = TSActivator.CreateInstance("Tekla.Structures.Model.BoltArray");
		}

		public System.Boolean AddBoltDistX(System.Double DistX)
			 => teklaObject.AddBoltDistX(DistX);

		public System.Boolean AddBoltDistY(System.Double DistY)
			 => teklaObject.AddBoltDistY(DistY);

		public System.Boolean RemoveBoltDistX(System.Int32 Index)
			 => teklaObject.RemoveBoltDistX(Index);

		public System.Boolean RemoveBoltDistY(System.Int32 Index)
			 => teklaObject.RemoveBoltDistY(Index);

		public System.Int32 GetBoltDistXCount()
			 => teklaObject.GetBoltDistXCount();

		public System.Int32 GetBoltDistYCount()
			 => teklaObject.GetBoltDistYCount();

		public System.Double GetBoltDistX(System.Int32 Index)
			 => teklaObject.GetBoltDistX(Index);

		public System.Double GetBoltDistY(System.Int32 Index)
			 => teklaObject.GetBoltDistY(Index);

		public System.Boolean SetBoltDistX(System.Int32 Index, System.Double DistX)
			 => teklaObject.SetBoltDistX(Index, DistX);

		public System.Boolean SetBoltDistY(System.Int32 Index, System.Double DistY)
			 => teklaObject.SetBoltDistY(Index, DistY);

		public System.Boolean Insert()
			 => teklaObject.Insert();

		public System.Boolean Select()
			 => teklaObject.Select();

		public System.Boolean Modify()
			 => teklaObject.Modify();

		public System.Boolean Delete()
			 => teklaObject.Delete();





    }

    internal static class BoltArray_
    {
        public static dynamic GetTSObject(BoltArray dynObject)
        {
            return dynObject.teklaObject;
        }

        public static BoltArray FromTSObject(dynamic tsObject)
        {
            var typeName = "Dynamic." + tsObject.GetType().FullName;
            var type = System.Reflection.Assembly.GetExecutingAssembly().GetType(typeName);
            var dynObject = (Tekla.Structures.Model.BoltArray)System.Activator.CreateInstance(type);
            dynObject.teklaObject = tsObject;
            return dynObject;
        }
    }


}
    
