//Generated by script in project CodeGenerator
//Copyright Dawid Dyrcz 2020 see license file

namespace Dynamic.Tekla.Structures.Model
{

    public  class LoadTemperature  : Dynamic.Tekla.Structures.Model.Load
    {

		public Dynamic.Tekla.Structures.Model.Load.LoadSpanningEnum Spanning
		{
			get => Dynamic.Tekla.Structures.Model.Load.LoadSpanningEnum_.FromTSObject(teklaObject.Spanning);
			set { teklaObject.Spanning = Dynamic.Tekla.Structures.Model.Load.LoadSpanningEnum_.GetTSObject(value); }
		}

		public Dynamic.Tekla.Structures.Geometry3d.Vector PrimaryAxisDirection
		{
			get => Dynamic.Tekla.Structures.Geometry3d.Vector_.FromTSObject(teklaObject.PrimaryAxisDirection);
			set { teklaObject.PrimaryAxisDirection = Dynamic.Tekla.Structures.Geometry3d.Vector_.GetTSObject(value); }
		}

		public System.Boolean AutomaticPrimaryAxisWeight
		{
			get => teklaObject.AutomaticPrimaryAxisWeight;
			set { teklaObject.AutomaticPrimaryAxisWeight = value; }
		}

		public System.Double Weight
		{
			get => teklaObject.Weight;
			set { teklaObject.Weight = value; }
		}

		public System.Double LoadDispersionAngle
		{
			get => teklaObject.LoadDispersionAngle;
			set { teklaObject.LoadDispersionAngle = value; }
		}

		public System.Boolean CreateFixedSupportConditionsAutomatically
		{
			get => teklaObject.CreateFixedSupportConditionsAutomatically;
			set { teklaObject.CreateFixedSupportConditionsAutomatically = value; }
		}

		public Dynamic.Tekla.Structures.Geometry3d.Point Position1
		{
			get => Dynamic.Tekla.Structures.Geometry3d.Point_.FromTSObject(teklaObject.Position1);
			set { teklaObject.Position1 = Dynamic.Tekla.Structures.Geometry3d.Point_.GetTSObject(value); }
		}

		public Dynamic.Tekla.Structures.Geometry3d.Point Position2
		{
			get => Dynamic.Tekla.Structures.Geometry3d.Point_.FromTSObject(teklaObject.Position2);
			set { teklaObject.Position2 = Dynamic.Tekla.Structures.Geometry3d.Point_.GetTSObject(value); }
		}

		public System.Double TemperatureChangeForAxialElongation
		{
			get => teklaObject.TemperatureChangeForAxialElongation;
			set { teklaObject.TemperatureChangeForAxialElongation = value; }
		}

		public System.Double TemperatureDifferentialTopToBottom
		{
			get => teklaObject.TemperatureDifferentialTopToBottom;
			set { teklaObject.TemperatureDifferentialTopToBottom = value; }
		}

		public System.Double TemperatureDifferentialSideToSide
		{
			get => teklaObject.TemperatureDifferentialSideToSide;
			set { teklaObject.TemperatureDifferentialSideToSide = value; }
		}

		public System.Double InitialAxialElongation
		{
			get => teklaObject.InitialAxialElongation;
			set { teklaObject.InitialAxialElongation = value; }
		}

        

        

		public LoadTemperature()
		{
			this.teklaObject = TSActivator.CreateInstance("Tekla.Structures.Model.LoadTemperature");
		}

		public System.Boolean Insert()
			 => teklaObject.Insert();

		public System.Boolean Select()
			 => teklaObject.Select();

		public System.Boolean Modify()
			 => teklaObject.Modify();

		public System.Boolean Delete()
			 => teklaObject.Delete();





    }

    internal static class LoadTemperature_
    {
        public static dynamic GetTSObject(LoadTemperature dynObject)
        {
            return dynObject.teklaObject;
        }

        public static LoadTemperature FromTSObject(dynamic tsObject)
        {
            var typeName = "Dynamic." + tsObject.GetType().FullName;
            var type = System.Reflection.Assembly.GetExecutingAssembly().GetType(typeName);
            var dynObject = (Tekla.Structures.Model.LoadTemperature)System.Activator.CreateInstance(type);
            dynObject.teklaObject = tsObject;
            return dynObject;
        }
    }


}
    
