//Generated by script in project CodeGenerator
//Copyright Dawid Dyrcz 2020 see license file

namespace Dynamic.Tekla.Structures.Model
{

    public  class PointCloud 
    {

		public System.Guid Guid
		{
			get => teklaObject.Guid;
			set { teklaObject.Guid = value; }
		}

		public System.String OriginalPath
		{
			get => teklaObject.OriginalPath;
			set { teklaObject.OriginalPath = value; }
		}

		public System.String Url
		{
			get => teklaObject.Url;
			set { teklaObject.Url = value; }
		}

		public System.String Name
		{
			get => teklaObject.Name;
			set { teklaObject.Name = value; }
		}

		public System.Guid LocationBy
		{
			get => teklaObject.LocationBy;
			set { teklaObject.LocationBy = value; }
		}

		public System.Boolean UseAutoCreatedBasePoint
		{
			get => teklaObject.UseAutoCreatedBasePoint;
			set { teklaObject.UseAutoCreatedBasePoint = value; }
		}

		public Dynamic.Tekla.Structures.Geometry3d.AABB BoundingBox
		{
			get => Dynamic.Tekla.Structures.Geometry3d.AABB_.FromTSObject(teklaObject.BoundingBox);
			set { teklaObject.BoundingBox = Dynamic.Tekla.Structures.Geometry3d.AABB_.GetTSObject(value); }
		}

		public System.Double Scale
		{
			get => teklaObject.Scale;
			set { teklaObject.Scale = value; }
		}

        

        internal dynamic teklaObject;

		public PointCloud()
		{
			this.teklaObject = TSActivator.CreateInstance("Tekla.Structures.Model.PointCloud");
		}

		public System.Boolean Attach()
			 => teklaObject.Attach();

		public System.Boolean AttachComplete()
			 => teklaObject.AttachComplete();

		public System.Boolean Detach()
			 => teklaObject.Detach();

		public System.Boolean Select()
			 => teklaObject.Select();

		public System.Boolean SetVisibility(System.Collections.Generic.List<Dynamic.Tekla.Structures.Model.UI.View> views, System.Boolean visible)
			 => teklaObject.SetVisibility(views, visible);

		public System.Collections.Generic.List<Dynamic.Tekla.Structures.Model.UI.View> GetVisibleInViews()
			 => teklaObject.GetVisibleInViews();

		public System.Collections.Generic.List<Dynamic.Tekla.Structures.Model.PointCloud> GetPointClouds()
			 => teklaObject.GetPointClouds();





    }

    internal static class PointCloud_
    {
        public static dynamic GetTSObject(PointCloud dynObject)
        {
            return dynObject.teklaObject;
        }

        public static PointCloud FromTSObject(dynamic tsObject)
        {
            return new PointCloud() { teklaObject = tsObject };
        }
    }


}
    
