//Generated by script in project CodeGenerator
//Copyright Dawid Dyrcz 2020 see license file

namespace Dynamic.Tekla.Structures.Model
{

    public  class RebarGeometry 
    {

		public Dynamic.Tekla.Structures.Geometry3d.PolyLine Shape
		{
			get => Dynamic.Tekla.Structures.Geometry3d.PolyLine_.FromTSObject(teklaObject.Shape);
			set { teklaObject.Shape = Dynamic.Tekla.Structures.Geometry3d.PolyLine_.GetTSObject(value); }
		}

		public System.Double Diameter
		{
			get => teklaObject.Diameter;
			set { teklaObject.Diameter = value; }
		}

		public System.Collections.ArrayList BendingRadiuses
		{
			get => teklaObject.BendingRadiuses;
			set { teklaObject.BendingRadiuses = value; }
		}

        

        internal dynamic teklaObject;

		public RebarGeometry() {}





    }

    internal static class RebarGeometry_
    {
        public static dynamic GetTSObject(RebarGeometry dynObject)
        {
            return dynObject.teklaObject;
        }

        public static RebarGeometry FromTSObject(dynamic tsObject)
        {
            var typeName = "Dynamic." + tsObject.GetType().FullName;
            var type = System.Reflection.Assembly.GetExecutingAssembly().GetType(typeName);
            var dynObject = (Tekla.Structures.Model.RebarGeometry)System.Activator.CreateInstance(type);
            dynObject.teklaObject = tsObject;
            return dynObject;
        }
    }


}
    
