//Generated by script in project CodeGenerator
//Copyright Dawid Dyrcz 2020 see license file

namespace Dynamic.Tekla.Structures.Geometry3d
{

    public sealed class Arc 
    {

		public System.Double Length
		{
			get => arc.Length;
			set { arc.Length = value; }
		}

		public Dynamic.Tekla.Structures.Geometry3d.Point StartPoint
		{
			get => new Dynamic.Tekla.Structures.Geometry3d.Point(arc.StartPoint.GetTSObject());
			set { arc.StartPoint = value.GetTSObject(); }
		}

		public Dynamic.Tekla.Structures.Geometry3d.Point EndPoint
		{
			get => new Dynamic.Tekla.Structures.Geometry3d.Point(arc.EndPoint.GetTSObject());
			set { arc.EndPoint = value.GetTSObject(); }
		}

		public Dynamic.Tekla.Structures.Geometry3d.Point CenterPoint
		{
			get => new Dynamic.Tekla.Structures.Geometry3d.Point(arc.CenterPoint.GetTSObject());
			set { arc.CenterPoint = value.GetTSObject(); }
		}

		public Dynamic.Tekla.Structures.Geometry3d.Point ArcMiddlePoint
		{
			get => new Dynamic.Tekla.Structures.Geometry3d.Point(arc.ArcMiddlePoint.GetTSObject());
			set { arc.ArcMiddlePoint = value.GetTSObject(); }
		}

		public Dynamic.Tekla.Structures.Geometry3d.Vector Normal
		{
			get => new Dynamic.Tekla.Structures.Geometry3d.Vector(arc.Normal.GetTSObject());
			set { arc.Normal = value.GetTSObject(); }
		}

		public System.Double Angle
		{
			get => arc.Angle;
			set { arc.Angle = value; }
		}

		public System.Double Radius
		{
			get => arc.Radius;
			set { arc.Radius = value; }
		}

		public Dynamic.Tekla.Structures.Geometry3d.Vector StartTangent
		{
			get => new Dynamic.Tekla.Structures.Geometry3d.Vector(arc.StartTangent.GetTSObject());
			set { arc.StartTangent = value.GetTSObject(); }
		}

		public Dynamic.Tekla.Structures.Geometry3d.Vector StartDirection
		{
			get => new Dynamic.Tekla.Structures.Geometry3d.Vector(arc.StartDirection.GetTSObject());
			set { arc.StartDirection = value.GetTSObject(); }
		}

        

        dynamic arc;
        
        public Arc()
        {
            this.arc =  new Tekla.Structures.Geometry3d.Arc();
        }

        public Arc(dynamic tsObject)
        {
            this.arc = tsObject;
			this.Length = arc.Length;
			this.StartPoint = new Dynamic.Tekla.Structures.Geometry3d.Point(arc.StartPoint);
			this.EndPoint = new Dynamic.Tekla.Structures.Geometry3d.Point(arc.EndPoint);
			this.CenterPoint = new Dynamic.Tekla.Structures.Geometry3d.Point(arc.CenterPoint);
			this.ArcMiddlePoint = new Dynamic.Tekla.Structures.Geometry3d.Point(arc.ArcMiddlePoint);
			this.Normal = new Dynamic.Tekla.Structures.Geometry3d.Vector(arc.Normal);
			this.Angle = arc.Angle;
			this.Radius = arc.Radius;
			this.StartTangent = new Dynamic.Tekla.Structures.Geometry3d.Vector(arc.StartTangent);
			this.StartDirection = new Dynamic.Tekla.Structures.Geometry3d.Vector(arc.StartDirection);

        }


        public dynamic GetTSObject() => arc;

		public Dynamic.Tekla.Structures.Geometry3d.ICurve Clone()
			 => new Dynamic.Tekla.Structures.Geometry3d.ICurve(arc.Clone());

		public System.Boolean Equals(System.Object other)
			 => arc.Equals(other);

		public System.Boolean Equals(Dynamic.Tekla.Structures.Geometry3d.ICurve other)
			 => arc.Equals(other.GetTSObject());

		public System.Int32 GetHashCode()
			 => arc.GetHashCode();

		public System.Type GetType()
			 => arc.GetType();

		public System.String ToString()
			 => arc.ToString();





    }

}
    
