//Generated by script in project CodeGenerator
//Copyright Dawid Dyrcz 2020 see license file

namespace Dynamic.Tekla.Structures.Model
{

    public sealed class BentPlateGeometrySolver 
    {

        

        dynamic bentplategeometrysolver;
        
        public BentPlateGeometrySolver()
        {
            this.bentplategeometrysolver =  new Tekla.Structures.Model.BentPlateGeometrySolver();
        }

        public BentPlateGeometrySolver(dynamic tsObject)
        {
            this.bentplategeometrysolver = tsObject;

        }


        public dynamic GetTSObject() => bentplategeometrysolver;

		public Dynamic.Tekla.Structures.Model.ConnectiveGeometry AddLeg(Dynamic.Tekla.Structures.Model.ConnectiveGeometry geometry, Dynamic.Tekla.Structures.Model.Contour polygon, Dynamic.Tekla.Structures.Model.BendShape bendShape)
			 => new Dynamic.Tekla.Structures.Model.ConnectiveGeometry(bentplategeometrysolver.AddLeg(geometry.GetTSObject(), polygon.GetTSObject(), bendShape.GetTSObject()));

		public Dynamic.Tekla.Structures.Model.ConnectiveGeometry AddLeg(Dynamic.Tekla.Structures.Model.ConnectiveGeometry geometry, Dynamic.Tekla.Structures.Model.Contour polygon)
			 => new Dynamic.Tekla.Structures.Model.ConnectiveGeometry(bentplategeometrysolver.AddLeg(geometry.GetTSObject(), polygon.GetTSObject()));

		public Dynamic.Tekla.Structures.Model.ConnectiveGeometry AddLeg(Dynamic.Tekla.Structures.Model.ConnectiveGeometry geometry, Dynamic.Tekla.Structures.Model.Contour polygon, System.Double radius)
			 => new Dynamic.Tekla.Structures.Model.ConnectiveGeometry(bentplategeometrysolver.AddLeg(geometry.GetTSObject(), polygon.GetTSObject(), radius));

		public Dynamic.Tekla.Structures.Model.ConnectiveGeometry AddLeg(Dynamic.Tekla.Structures.Model.ConnectiveGeometry geometry, Dynamic.Tekla.Structures.Model.Contour polygon, System.Double largestRadius, System.Double halfAperture)
			 => new Dynamic.Tekla.Structures.Model.ConnectiveGeometry(bentplategeometrysolver.AddLeg(geometry.GetTSObject(), polygon.GetTSObject(), largestRadius, halfAperture));

		public Dynamic.Tekla.Structures.Model.ConnectiveGeometry AddLeg(Dynamic.Tekla.Structures.Model.ConnectiveGeometry geometry, Dynamic.Tekla.Structures.Geometry3d.LineSegment segment1, Dynamic.Tekla.Structures.Model.Contour polygon, Dynamic.Tekla.Structures.Geometry3d.LineSegment segment2, Dynamic.Tekla.Structures.Model.BendShape bendShape)
			 => new Dynamic.Tekla.Structures.Model.ConnectiveGeometry(bentplategeometrysolver.AddLeg(geometry.GetTSObject(), segment1.GetTSObject(), polygon.GetTSObject(), segment2.GetTSObject(), bendShape.GetTSObject()));

		public Dynamic.Tekla.Structures.Model.ConnectiveGeometry AddLeg(Dynamic.Tekla.Structures.Model.ConnectiveGeometry geometry, Dynamic.Tekla.Structures.Geometry3d.LineSegment segment1, Dynamic.Tekla.Structures.Model.Contour polygon, Dynamic.Tekla.Structures.Geometry3d.LineSegment segment2)
			 => new Dynamic.Tekla.Structures.Model.ConnectiveGeometry(bentplategeometrysolver.AddLeg(geometry.GetTSObject(), segment1.GetTSObject(), polygon.GetTSObject(), segment2.GetTSObject()));

		public Dynamic.Tekla.Structures.Model.ConnectiveGeometry AddLeg(Dynamic.Tekla.Structures.Model.ConnectiveGeometry geometry, Dynamic.Tekla.Structures.Geometry3d.LineSegment segment1, Dynamic.Tekla.Structures.Model.Contour polygon, Dynamic.Tekla.Structures.Geometry3d.LineSegment segment2, System.Double radius)
			 => new Dynamic.Tekla.Structures.Model.ConnectiveGeometry(bentplategeometrysolver.AddLeg(geometry.GetTSObject(), segment1.GetTSObject(), polygon.GetTSObject(), segment2.GetTSObject(), radius));

		public Dynamic.Tekla.Structures.Model.ConnectiveGeometry AddLeg(Dynamic.Tekla.Structures.Model.ConnectiveGeometry geometry, Dynamic.Tekla.Structures.Geometry3d.LineSegment segment1, Dynamic.Tekla.Structures.Model.Contour polygon, Dynamic.Tekla.Structures.Geometry3d.LineSegment segment2, System.Double largestRadius, System.Double halfAperture)
			 => new Dynamic.Tekla.Structures.Model.ConnectiveGeometry(bentplategeometrysolver.AddLeg(geometry.GetTSObject(), segment1.GetTSObject(), polygon.GetTSObject(), segment2.GetTSObject(), largestRadius, halfAperture));

		public Dynamic.Tekla.Structures.Model.ConnectiveGeometry RemoveLeg(Dynamic.Tekla.Structures.Model.ConnectiveGeometry geometry, Dynamic.Tekla.Structures.Model.GeometrySection legSection)
			 => new Dynamic.Tekla.Structures.Model.ConnectiveGeometry(bentplategeometrysolver.RemoveLeg(geometry.GetTSObject(), legSection.GetTSObject()));

		public System.Collections.Generic.IList<Dynamic.Tekla.Structures.Model.ConnectiveGeometry> Split(Dynamic.Tekla.Structures.Model.ConnectiveGeometry geometry, Dynamic.Tekla.Structures.Model.GeometrySection geometrySection)
			 => bentplategeometrysolver.Split(geometry.GetTSObject(), geometrySection.GetTSObject());

		public Dynamic.Tekla.Structures.Model.ConnectiveGeometry ModifyBendSurface(Dynamic.Tekla.Structures.Model.ConnectiveGeometry geometry, Dynamic.Tekla.Structures.Model.GeometrySection bendSection, Dynamic.Tekla.Structures.Model.BendSurface surface)
			 => new Dynamic.Tekla.Structures.Model.ConnectiveGeometry(bentplategeometrysolver.ModifyBendSurface(geometry.GetTSObject(), bendSection.GetTSObject(), surface.GetTSObject()));

		public Dynamic.Tekla.Structures.Model.ConnectiveGeometry ModifyCylindricalSurface(Dynamic.Tekla.Structures.Model.ConnectiveGeometry geometry, Dynamic.Tekla.Structures.Model.GeometrySection cylindricalSection, Dynamic.Tekla.Structures.Model.CylindricalSurface surface)
			 => new Dynamic.Tekla.Structures.Model.ConnectiveGeometry(bentplategeometrysolver.ModifyCylindricalSurface(geometry.GetTSObject(), cylindricalSection.GetTSObject(), surface.GetTSObject()));

		public Dynamic.Tekla.Structures.Model.ConnectiveGeometry ModifyRadius(Dynamic.Tekla.Structures.Model.ConnectiveGeometry geometry, Dynamic.Tekla.Structures.Model.GeometrySection cylindricalSection, System.Double radius)
			 => new Dynamic.Tekla.Structures.Model.ConnectiveGeometry(bentplategeometrysolver.ModifyRadius(geometry.GetTSObject(), cylindricalSection.GetTSObject(), radius));

		public Dynamic.Tekla.Structures.Model.ConnectiveGeometry ModifyConicalRadiuses(Dynamic.Tekla.Structures.Model.ConnectiveGeometry geometry, Dynamic.Tekla.Structures.Model.GeometrySection conicalSection, System.Double radius1, System.Double radius2)
			 => new Dynamic.Tekla.Structures.Model.ConnectiveGeometry(bentplategeometrysolver.ModifyConicalRadiuses(geometry.GetTSObject(), conicalSection.GetTSObject(), radius1, radius2));

		public Dynamic.Tekla.Structures.Model.ConnectiveGeometry ScaleConeSection(Dynamic.Tekla.Structures.Model.ConnectiveGeometry geometry, Dynamic.Tekla.Structures.Model.GeometrySection conicalSection, System.Double scale)
			 => new Dynamic.Tekla.Structures.Model.ConnectiveGeometry(bentplategeometrysolver.ScaleConeSection(geometry.GetTSObject(), conicalSection.GetTSObject(), scale));

		public Dynamic.Tekla.Structures.Model.ConnectiveGeometry ModifyPolygon(Dynamic.Tekla.Structures.Model.ConnectiveGeometry geometry, Dynamic.Tekla.Structures.Model.GeometrySection polygonSection, Dynamic.Tekla.Structures.Model.Contour points)
			 => new Dynamic.Tekla.Structures.Model.ConnectiveGeometry(bentplategeometrysolver.ModifyPolygon(geometry.GetTSObject(), polygonSection.GetTSObject(), points.GetTSObject()));

		public Dynamic.Tekla.Structures.Model.ConnectiveGeometry SetMainSection(Dynamic.Tekla.Structures.Model.GeometrySection newMainSection, Dynamic.Tekla.Structures.Model.ConnectiveGeometry geometry)
			 => new Dynamic.Tekla.Structures.Model.ConnectiveGeometry(bentplategeometrysolver.SetMainSection(newMainSection.GetTSObject(), geometry.GetTSObject()));

		public Dynamic.Tekla.Structures.Model.ConnectiveGeometry SetBendAngle(System.Double angle, Dynamic.Tekla.Structures.Model.GeometrySection sectionToSetAngle, Dynamic.Tekla.Structures.Model.GeometrySection sectionToMove, Dynamic.Tekla.Structures.Model.ConnectiveGeometry geometry)
			 => new Dynamic.Tekla.Structures.Model.ConnectiveGeometry(bentplategeometrysolver.SetBendAngle(angle, sectionToSetAngle.GetTSObject(), sectionToMove.GetTSObject(), geometry.GetTSObject()));

		public System.Boolean Equals(System.Object obj)
			 => bentplategeometrysolver.Equals(obj);

		public System.Int32 GetHashCode()
			 => bentplategeometrysolver.GetHashCode();

		public System.Type GetType()
			 => bentplategeometrysolver.GetType();

		public System.String ToString()
			 => bentplategeometrysolver.ToString();




    public enum OperationStatus
    {
			Success,
			Failure,
			FacePerpendicularToIntersectionLine,
			PlateIntersectsWithIntersectionLine,
			ExtensionIntersectsWithPlate,
			FacesTooNearEachOther,
			FacesAtAnObtuseAngle,
			UndefinedCurveDirection,
			UnsupportedChamfer,
			InvalidRadius,
			InvalidFacePoints        
    }

    public static class OperationStatus_
    {
        public static dynamic GetTSObject(OperationStatus dynEnum)
        {
            var tsType = TSActivator.CreateInstance("Tekla.Structures.Model.OperationStatus");

            switch (dynEnum)
            {
				case OperationStatus.Success:
					return System.Enum.Parse(tsType, "Success");
				case OperationStatus.Failure:
					return System.Enum.Parse(tsType, "Failure");
				case OperationStatus.FacePerpendicularToIntersectionLine:
					return System.Enum.Parse(tsType, "FacePerpendicularToIntersectionLine");
				case OperationStatus.PlateIntersectsWithIntersectionLine:
					return System.Enum.Parse(tsType, "PlateIntersectsWithIntersectionLine");
				case OperationStatus.ExtensionIntersectsWithPlate:
					return System.Enum.Parse(tsType, "ExtensionIntersectsWithPlate");
				case OperationStatus.FacesTooNearEachOther:
					return System.Enum.Parse(tsType, "FacesTooNearEachOther");
				case OperationStatus.FacesAtAnObtuseAngle:
					return System.Enum.Parse(tsType, "FacesAtAnObtuseAngle");
				case OperationStatus.UndefinedCurveDirection:
					return System.Enum.Parse(tsType, "UndefinedCurveDirection");
				case OperationStatus.UnsupportedChamfer:
					return System.Enum.Parse(tsType, "UnsupportedChamfer");
				case OperationStatus.InvalidRadius:
					return System.Enum.Parse(tsType, "InvalidRadius");
				case OperationStatus.InvalidFacePoints:
					return System.Enum.Parse(tsType, "InvalidFacePoints");

                default:
                    throw new System.NotImplementedException(dynEnum.ToString() + "- enum value is not implemented");
            }
        }
    
        public static OperationStatus FromTSObject(dynamic tsEnum)
        {
            string tsEnumValue = tsEnum.ToString("G", System.Globalization.CultureInfo.InvariantCulture);
            
			if (tsEnumValue.Equals("Success", System.StringComparison.InvariantCulture))
				return OperationStatus.Success;
			else if (tsEnumValue.Equals("Failure", System.StringComparison.InvariantCulture))
				return OperationStatus.Failure;
			else if (tsEnumValue.Equals("FacePerpendicularToIntersectionLine", System.StringComparison.InvariantCulture))
				return OperationStatus.FacePerpendicularToIntersectionLine;
			else if (tsEnumValue.Equals("PlateIntersectsWithIntersectionLine", System.StringComparison.InvariantCulture))
				return OperationStatus.PlateIntersectsWithIntersectionLine;
			else if (tsEnumValue.Equals("ExtensionIntersectsWithPlate", System.StringComparison.InvariantCulture))
				return OperationStatus.ExtensionIntersectsWithPlate;
			else if (tsEnumValue.Equals("FacesTooNearEachOther", System.StringComparison.InvariantCulture))
				return OperationStatus.FacesTooNearEachOther;
			else if (tsEnumValue.Equals("FacesAtAnObtuseAngle", System.StringComparison.InvariantCulture))
				return OperationStatus.FacesAtAnObtuseAngle;
			else if (tsEnumValue.Equals("UndefinedCurveDirection", System.StringComparison.InvariantCulture))
				return OperationStatus.UndefinedCurveDirection;
			else if (tsEnumValue.Equals("UnsupportedChamfer", System.StringComparison.InvariantCulture))
				return OperationStatus.UnsupportedChamfer;
			else if (tsEnumValue.Equals("InvalidRadius", System.StringComparison.InvariantCulture))
				return OperationStatus.InvalidRadius;
			else if (tsEnumValue.Equals("InvalidFacePoints", System.StringComparison.InvariantCulture))
				return OperationStatus.InvalidFacePoints;

            else 
                throw new System.NotImplementedException(tsEnumValue + "- enum value is not implemented");
            
        }
    }



    }

}
    
