//Generated by script in project CodeGenerator
//Copyright Dawid Dyrcz 2020 see license file

namespace Dynamic.Tekla.Structures.Model
{

    public sealed class ConicalSurface 
    {

		public System.TupleSystem.Double, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089,System.Double, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089<System.Double, System.Double> Radiuses
		{
			get => conicalsurface.Radiuses;
			set { conicalsurface.Radiuses = value; }
		}

		public Dynamic.Tekla.Structures.Geometry3d.Point Apex
		{
			get => new Dynamic.Tekla.Structures.Geometry3d.Point(conicalsurface.Apex.GetTSObject());
			set { conicalsurface.Apex = value.GetTSObject(); }
		}

		public System.Boolean InwardCurved
		{
			get => conicalsurface.InwardCurved;
			set { conicalsurface.InwardCurved = value; }
		}

		public Dynamic.Tekla.Structures.Geometry3d.Line IntersectionLine
		{
			get => new Dynamic.Tekla.Structures.Geometry3d.Line(conicalsurface.IntersectionLine.GetTSObject());
			set { conicalsurface.IntersectionLine = value.GetTSObject(); }
		}

		public Dynamic.Tekla.Structures.Geometry3d.Vector EndFaceNormal1
		{
			get => new Dynamic.Tekla.Structures.Geometry3d.Vector(conicalsurface.EndFaceNormal1.GetTSObject());
			set { conicalsurface.EndFaceNormal1 = value.GetTSObject(); }
		}

		public Dynamic.Tekla.Structures.Geometry3d.Vector EndFaceNormal2
		{
			get => new Dynamic.Tekla.Structures.Geometry3d.Vector(conicalsurface.EndFaceNormal2.GetTSObject());
			set { conicalsurface.EndFaceNormal2 = value.GetTSObject(); }
		}

		public Dynamic.Tekla.Structures.Geometry3d.Line CenterLine
		{
			get => new Dynamic.Tekla.Structures.Geometry3d.Line(conicalsurface.CenterLine.GetTSObject());
			set { conicalsurface.CenterLine = value.GetTSObject(); }
		}

		public Dynamic.Tekla.Structures.Geometry3d.Vector RotationAxis
		{
			get => new Dynamic.Tekla.Structures.Geometry3d.Vector(conicalsurface.RotationAxis.GetTSObject());
			set { conicalsurface.RotationAxis = value.GetTSObject(); }
		}

		public System.Collections.Generic.ListTekla.Structures.Geometry3d.Point, Tekla.Structures, Version=2019.1.0.0, Culture=neutral, PublicKeyToken=2f04dbe497b71114<Dynamic.Tekla.Structures.Geometry3d.Point> LateralBoundary1
		{
			get => conicalsurface.LateralBoundary1;
			set { conicalsurface.LateralBoundary1 = value; }
		}

		public System.Collections.Generic.ListTekla.Structures.Geometry3d.Point, Tekla.Structures, Version=2019.1.0.0, Culture=neutral, PublicKeyToken=2f04dbe497b71114<Dynamic.Tekla.Structures.Geometry3d.Point> LateralBoundary2
		{
			get => conicalsurface.LateralBoundary2;
			set { conicalsurface.LateralBoundary2 = value; }
		}

		public Dynamic.Tekla.Structures.Geometry3d.LineSegment SideBoundary1
		{
			get => new Dynamic.Tekla.Structures.Geometry3d.LineSegment(conicalsurface.SideBoundary1.GetTSObject());
			set { conicalsurface.SideBoundary1 = value.GetTSObject(); }
		}

		public Dynamic.Tekla.Structures.Geometry3d.LineSegment SideBoundary2
		{
			get => new Dynamic.Tekla.Structures.Geometry3d.LineSegment(conicalsurface.SideBoundary2.GetTSObject());
			set { conicalsurface.SideBoundary2 = value.GetTSObject(); }
		}

        

        dynamic conicalsurface;
        
        public ConicalSurface()
        {
            this.conicalsurface =  new Tekla.Structures.Model.ConicalSurface();
        }

        public ConicalSurface(dynamic tsObject)
        {
            this.conicalsurface = tsObject;
			this.Radiuses = conicalsurface.Radiuses;
			this.Apex = new Dynamic.Tekla.Structures.Geometry3d.Point(conicalsurface.Apex);
			this.InwardCurved = conicalsurface.InwardCurved;
			this.IntersectionLine = new Dynamic.Tekla.Structures.Geometry3d.Line(conicalsurface.IntersectionLine);
			this.EndFaceNormal1 = new Dynamic.Tekla.Structures.Geometry3d.Vector(conicalsurface.EndFaceNormal1);
			this.EndFaceNormal2 = new Dynamic.Tekla.Structures.Geometry3d.Vector(conicalsurface.EndFaceNormal2);
			this.CenterLine = new Dynamic.Tekla.Structures.Geometry3d.Line(conicalsurface.CenterLine);
			this.RotationAxis = new Dynamic.Tekla.Structures.Geometry3d.Vector(conicalsurface.RotationAxis);
			this.LateralBoundary1 = conicalsurface.LateralBoundary1;
			this.LateralBoundary2 = conicalsurface.LateralBoundary2;
			this.SideBoundary1 = new Dynamic.Tekla.Structures.Geometry3d.LineSegment(conicalsurface.SideBoundary1);
			this.SideBoundary2 = new Dynamic.Tekla.Structures.Geometry3d.LineSegment(conicalsurface.SideBoundary2);

        }


        public dynamic GetTSObject() => conicalsurface;

		public System.Boolean Equals(System.Object obj)
			 => conicalsurface.Equals(obj);

		public System.Int32 GetHashCode()
			 => conicalsurface.GetHashCode();

		public System.Type GetType()
			 => conicalsurface.GetType();

		public System.String ToString()
			 => conicalsurface.ToString();





    }

}
    
