//Generated by script in project CodeGenerator
//Copyright Dawid Dyrcz 2020 see license file

namespace Dynamic.Tekla.Structures.Model
{

    public sealed class CylindricalSurfaceNode 
    {

		public Dynamic.Tekla.Structures.Model.CylindricalSurface Surface
		{
			get => new Dynamic.Tekla.Structures.Model.CylindricalSurface(cylindricalsurfacenode.Surface.GetTSObject());
			set { cylindricalsurfacenode.Surface = value.GetTSObject(); }
		}

		public System.Boolean IsAutomatic
		{
			get => cylindricalsurfacenode.IsAutomatic;
			set { cylindricalsurfacenode.IsAutomatic = value; }
		}

		public Dynamic.Tekla.Structures.Model.BendSurface Surface
		{
			get => new Dynamic.Tekla.Structures.Model.BendSurface(cylindricalsurfacenode.Surface.GetTSObject());
			set { cylindricalsurfacenode.Surface = value.GetTSObject(); }
		}

        

        dynamic cylindricalsurfacenode;
        
        public CylindricalSurfaceNode()
        {
            this.cylindricalsurfacenode =  new Tekla.Structures.Model.CylindricalSurfaceNode();
        }

        public CylindricalSurfaceNode(dynamic tsObject)
        {
            this.cylindricalsurfacenode = tsObject;
			this.Surface = new Dynamic.Tekla.Structures.Model.CylindricalSurface(cylindricalsurfacenode.Surface);
			this.IsAutomatic = cylindricalsurfacenode.IsAutomatic;
			this.Surface = new Dynamic.Tekla.Structures.Model.BendSurface(cylindricalsurfacenode.Surface);

        }


        public dynamic GetTSObject() => cylindricalsurfacenode;

		public void AcceptVisitor(Dynamic.Tekla.Structures.Model.IGeometryNodeVisitor visitor)
			 => cylindricalsurfacenode.AcceptVisitor(visitor.GetTSObject());

		public Dynamic.Tekla.Structures.Model.IGeometryNode Clone()
			 => new Dynamic.Tekla.Structures.Model.IGeometryNode(cylindricalsurfacenode.Clone());





    }

}
    
