//Generated by script in project CodeGenerator
//Copyright Dawid Dyrcz 2020 see license file

namespace Dynamic.Tekla.Structures.Model.Collaboration
{

    public sealed class IFC2X3_ParametricObject_CircleHollowProfile 
    {

		public System.Double Radius
		{
			get => ifc2x3_parametricobject_circlehollowprofile.Radius;
			set { ifc2x3_parametricobject_circlehollowprofile.Radius = value; }
		}

		public System.Double WallThickness
		{
			get => ifc2x3_parametricobject_circlehollowprofile.WallThickness;
			set { ifc2x3_parametricobject_circlehollowprofile.WallThickness = value; }
		}

		public Dynamic.Tekla.Structures.Geometry3d.Point Origin
		{
			get => new Dynamic.Tekla.Structures.Geometry3d.Point(ifc2x3_parametricobject_circlehollowprofile.Origin.GetTSObject());
			set { ifc2x3_parametricobject_circlehollowprofile.Origin = value.GetTSObject(); }
		}

		public Dynamic.Tekla.Structures.Geometry3d.Vector xDir
		{
			get => new Dynamic.Tekla.Structures.Geometry3d.Vector(ifc2x3_parametricobject_circlehollowprofile.xDir.GetTSObject());
			set { ifc2x3_parametricobject_circlehollowprofile.xDir = value.GetTSObject(); }
		}

		public Dynamic.Tekla.Structures.Geometry3d.Vector Extrusion
		{
			get => new Dynamic.Tekla.Structures.Geometry3d.Vector(ifc2x3_parametricobject_circlehollowprofile.Extrusion.GetTSObject());
			set { ifc2x3_parametricobject_circlehollowprofile.Extrusion = value.GetTSObject(); }
		}

		public System.String ProfileName
		{
			get => ifc2x3_parametricobject_circlehollowprofile.ProfileName;
			set { ifc2x3_parametricobject_circlehollowprofile.ProfileName = value; }
		}

		public System.String Name
		{
			get => ifc2x3_parametricobject_circlehollowprofile.Name;
			set { ifc2x3_parametricobject_circlehollowprofile.Name = value; }
		}

		public System.String Description
		{
			get => ifc2x3_parametricobject_circlehollowprofile.Description;
			set { ifc2x3_parametricobject_circlehollowprofile.Description = value; }
		}

		public System.String ObjectType
		{
			get => ifc2x3_parametricobject_circlehollowprofile.ObjectType;
			set { ifc2x3_parametricobject_circlehollowprofile.ObjectType = value; }
		}

        

        dynamic ifc2x3_parametricobject_circlehollowprofile;
        
        public IFC2X3_ParametricObject_CircleHollowProfile()
        {
            this.ifc2x3_parametricobject_circlehollowprofile =  TSActivator.CreateInstance("Tekla.Structures.Model.Collaboration.IFC2X3_ParametricObject_CircleHollowProfile");
        }

        public IFC2X3_ParametricObject_CircleHollowProfile(dynamic tsObject)
        {
            this.ifc2x3_parametricobject_circlehollowprofile = tsObject;
			this.Radius = ifc2x3_parametricobject_circlehollowprofile.Radius;
			this.WallThickness = ifc2x3_parametricobject_circlehollowprofile.WallThickness;
			this.Origin = new Dynamic.Tekla.Structures.Geometry3d.Point(ifc2x3_parametricobject_circlehollowprofile.Origin);
			this.xDir = new Dynamic.Tekla.Structures.Geometry3d.Vector(ifc2x3_parametricobject_circlehollowprofile.xDir);
			this.Extrusion = new Dynamic.Tekla.Structures.Geometry3d.Vector(ifc2x3_parametricobject_circlehollowprofile.Extrusion);
			this.ProfileName = ifc2x3_parametricobject_circlehollowprofile.ProfileName;
			this.Name = ifc2x3_parametricobject_circlehollowprofile.Name;
			this.Description = ifc2x3_parametricobject_circlehollowprofile.Description;
			this.ObjectType = ifc2x3_parametricobject_circlehollowprofile.ObjectType;

        }


        public dynamic GetTSObject() => ifc2x3_parametricobject_circlehollowprofile;





    }

}
    
