//Generated by script in project CodeGenerator
//Copyright Dawid Dyrcz 2020 see license file

namespace Dynamic.Tekla.Structures.Model.Collaboration
{

    public sealed class IFC2X3_ParametricObject_RectangleProfile 
    {

		public System.Double XDim
		{
			get => ifc2x3_parametricobject_rectangleprofile.XDim;
			set { ifc2x3_parametricobject_rectangleprofile.XDim = value; }
		}

		public System.Double YDim
		{
			get => ifc2x3_parametricobject_rectangleprofile.YDim;
			set { ifc2x3_parametricobject_rectangleprofile.YDim = value; }
		}

		public Dynamic.Tekla.Structures.Geometry3d.Point Origin
		{
			get => new Dynamic.Tekla.Structures.Geometry3d.Point(ifc2x3_parametricobject_rectangleprofile.Origin.GetTSObject());
			set { ifc2x3_parametricobject_rectangleprofile.Origin = value.GetTSObject(); }
		}

		public Dynamic.Tekla.Structures.Geometry3d.Vector xDir
		{
			get => new Dynamic.Tekla.Structures.Geometry3d.Vector(ifc2x3_parametricobject_rectangleprofile.xDir.GetTSObject());
			set { ifc2x3_parametricobject_rectangleprofile.xDir = value.GetTSObject(); }
		}

		public Dynamic.Tekla.Structures.Geometry3d.Vector Extrusion
		{
			get => new Dynamic.Tekla.Structures.Geometry3d.Vector(ifc2x3_parametricobject_rectangleprofile.Extrusion.GetTSObject());
			set { ifc2x3_parametricobject_rectangleprofile.Extrusion = value.GetTSObject(); }
		}

		public System.String ProfileName
		{
			get => ifc2x3_parametricobject_rectangleprofile.ProfileName;
			set { ifc2x3_parametricobject_rectangleprofile.ProfileName = value; }
		}

		public System.String Name
		{
			get => ifc2x3_parametricobject_rectangleprofile.Name;
			set { ifc2x3_parametricobject_rectangleprofile.Name = value; }
		}

		public System.String Description
		{
			get => ifc2x3_parametricobject_rectangleprofile.Description;
			set { ifc2x3_parametricobject_rectangleprofile.Description = value; }
		}

		public System.String ObjectType
		{
			get => ifc2x3_parametricobject_rectangleprofile.ObjectType;
			set { ifc2x3_parametricobject_rectangleprofile.ObjectType = value; }
		}

        

        dynamic ifc2x3_parametricobject_rectangleprofile;
        
        public IFC2X3_ParametricObject_RectangleProfile()
        {
            this.ifc2x3_parametricobject_rectangleprofile =  new Tekla.Structures.Model.Collaboration.IFC2X3_ParametricObject_RectangleProfile();
        }

        public IFC2X3_ParametricObject_RectangleProfile(dynamic tsObject)
        {
            this.ifc2x3_parametricobject_rectangleprofile = tsObject;
			this.XDim = ifc2x3_parametricobject_rectangleprofile.XDim;
			this.YDim = ifc2x3_parametricobject_rectangleprofile.YDim;
			this.Origin = new Dynamic.Tekla.Structures.Geometry3d.Point(ifc2x3_parametricobject_rectangleprofile.Origin);
			this.xDir = new Dynamic.Tekla.Structures.Geometry3d.Vector(ifc2x3_parametricobject_rectangleprofile.xDir);
			this.Extrusion = new Dynamic.Tekla.Structures.Geometry3d.Vector(ifc2x3_parametricobject_rectangleprofile.Extrusion);
			this.ProfileName = ifc2x3_parametricobject_rectangleprofile.ProfileName;
			this.Name = ifc2x3_parametricobject_rectangleprofile.Name;
			this.Description = ifc2x3_parametricobject_rectangleprofile.Description;
			this.ObjectType = ifc2x3_parametricobject_rectangleprofile.ObjectType;

        }


        public dynamic GetTSObject() => ifc2x3_parametricobject_rectangleprofile;

		public System.Boolean Equals(System.Object obj)
			 => ifc2x3_parametricobject_rectangleprofile.Equals(obj);

		public System.Int32 GetHashCode()
			 => ifc2x3_parametricobject_rectangleprofile.GetHashCode();

		public System.Type GetType()
			 => ifc2x3_parametricobject_rectangleprofile.GetType();

		public System.String ToString()
			 => ifc2x3_parametricobject_rectangleprofile.ToString();





    }

}
    
