//Generated by script in project CodeGenerator
//Copyright Dawid Dyrcz 2020 see license file

namespace Dynamic.Tekla.Structures.Model.Collaboration
{

    public sealed class IFC2X3_ParametricObject_CShapeProfile 
    {

		public System.Double Depth
		{
			get => ifc2x3_parametricobject_cshapeprofile.Depth;
			set { ifc2x3_parametricobject_cshapeprofile.Depth = value; }
		}

		public System.Double Width
		{
			get => ifc2x3_parametricobject_cshapeprofile.Width;
			set { ifc2x3_parametricobject_cshapeprofile.Width = value; }
		}

		public System.Double WallThickness
		{
			get => ifc2x3_parametricobject_cshapeprofile.WallThickness;
			set { ifc2x3_parametricobject_cshapeprofile.WallThickness = value; }
		}

		public System.Double Girth
		{
			get => ifc2x3_parametricobject_cshapeprofile.Girth;
			set { ifc2x3_parametricobject_cshapeprofile.Girth = value; }
		}

		public System.Double InternalFilletRadius
		{
			get => ifc2x3_parametricobject_cshapeprofile.InternalFilletRadius;
			set { ifc2x3_parametricobject_cshapeprofile.InternalFilletRadius = value; }
		}

		public Dynamic.Tekla.Structures.Geometry3d.Point Origin
		{
			get => new Dynamic.Tekla.Structures.Geometry3d.Point(ifc2x3_parametricobject_cshapeprofile.Origin.GetTSObject());
			set { ifc2x3_parametricobject_cshapeprofile.Origin = value.GetTSObject(); }
		}

		public Dynamic.Tekla.Structures.Geometry3d.Vector xDir
		{
			get => new Dynamic.Tekla.Structures.Geometry3d.Vector(ifc2x3_parametricobject_cshapeprofile.xDir.GetTSObject());
			set { ifc2x3_parametricobject_cshapeprofile.xDir = value.GetTSObject(); }
		}

		public Dynamic.Tekla.Structures.Geometry3d.Vector Extrusion
		{
			get => new Dynamic.Tekla.Structures.Geometry3d.Vector(ifc2x3_parametricobject_cshapeprofile.Extrusion.GetTSObject());
			set { ifc2x3_parametricobject_cshapeprofile.Extrusion = value.GetTSObject(); }
		}

		public System.String ProfileName
		{
			get => ifc2x3_parametricobject_cshapeprofile.ProfileName;
			set { ifc2x3_parametricobject_cshapeprofile.ProfileName = value; }
		}

		public System.String Name
		{
			get => ifc2x3_parametricobject_cshapeprofile.Name;
			set { ifc2x3_parametricobject_cshapeprofile.Name = value; }
		}

		public System.String Description
		{
			get => ifc2x3_parametricobject_cshapeprofile.Description;
			set { ifc2x3_parametricobject_cshapeprofile.Description = value; }
		}

		public System.String ObjectType
		{
			get => ifc2x3_parametricobject_cshapeprofile.ObjectType;
			set { ifc2x3_parametricobject_cshapeprofile.ObjectType = value; }
		}

        

        dynamic ifc2x3_parametricobject_cshapeprofile;
        
        public IFC2X3_ParametricObject_CShapeProfile()
        {
            this.ifc2x3_parametricobject_cshapeprofile =  new Tekla.Structures.Model.Collaboration.IFC2X3_ParametricObject_CShapeProfile();
        }

        public IFC2X3_ParametricObject_CShapeProfile(dynamic tsObject)
        {
            this.ifc2x3_parametricobject_cshapeprofile = tsObject;
			this.Depth = ifc2x3_parametricobject_cshapeprofile.Depth;
			this.Width = ifc2x3_parametricobject_cshapeprofile.Width;
			this.WallThickness = ifc2x3_parametricobject_cshapeprofile.WallThickness;
			this.Girth = ifc2x3_parametricobject_cshapeprofile.Girth;
			this.InternalFilletRadius = ifc2x3_parametricobject_cshapeprofile.InternalFilletRadius;
			this.Origin = new Dynamic.Tekla.Structures.Geometry3d.Point(ifc2x3_parametricobject_cshapeprofile.Origin);
			this.xDir = new Dynamic.Tekla.Structures.Geometry3d.Vector(ifc2x3_parametricobject_cshapeprofile.xDir);
			this.Extrusion = new Dynamic.Tekla.Structures.Geometry3d.Vector(ifc2x3_parametricobject_cshapeprofile.Extrusion);
			this.ProfileName = ifc2x3_parametricobject_cshapeprofile.ProfileName;
			this.Name = ifc2x3_parametricobject_cshapeprofile.Name;
			this.Description = ifc2x3_parametricobject_cshapeprofile.Description;
			this.ObjectType = ifc2x3_parametricobject_cshapeprofile.ObjectType;

        }


        public dynamic GetTSObject() => ifc2x3_parametricobject_cshapeprofile;

		public System.Boolean Equals(System.Object obj)
			 => ifc2x3_parametricobject_cshapeprofile.Equals(obj);

		public System.Int32 GetHashCode()
			 => ifc2x3_parametricobject_cshapeprofile.GetHashCode();

		public System.Type GetType()
			 => ifc2x3_parametricobject_cshapeprofile.GetType();

		public System.String ToString()
			 => ifc2x3_parametricobject_cshapeprofile.ToString();





    }

}
    
