//Generated by script in project CodeGenerator
//Copyright Dawid Dyrcz 2020 see license file

namespace Dynamic.Tekla.Structures.Model.Collaboration
{

    public sealed class IFC2X3_ParametricObject_CircleProfile 
    {

		public System.Double Radius
		{
			get => ifc2x3_parametricobject_circleprofile.Radius;
			set { ifc2x3_parametricobject_circleprofile.Radius = value; }
		}

		public Dynamic.Tekla.Structures.Geometry3d.Point Origin
		{
			get => new Dynamic.Tekla.Structures.Geometry3d.Point(ifc2x3_parametricobject_circleprofile.Origin.GetTSObject());
			set { ifc2x3_parametricobject_circleprofile.Origin = value.GetTSObject(); }
		}

		public Dynamic.Tekla.Structures.Geometry3d.Vector xDir
		{
			get => new Dynamic.Tekla.Structures.Geometry3d.Vector(ifc2x3_parametricobject_circleprofile.xDir.GetTSObject());
			set { ifc2x3_parametricobject_circleprofile.xDir = value.GetTSObject(); }
		}

		public Dynamic.Tekla.Structures.Geometry3d.Vector Extrusion
		{
			get => new Dynamic.Tekla.Structures.Geometry3d.Vector(ifc2x3_parametricobject_circleprofile.Extrusion.GetTSObject());
			set { ifc2x3_parametricobject_circleprofile.Extrusion = value.GetTSObject(); }
		}

		public System.String ProfileName
		{
			get => ifc2x3_parametricobject_circleprofile.ProfileName;
			set { ifc2x3_parametricobject_circleprofile.ProfileName = value; }
		}

		public System.String Name
		{
			get => ifc2x3_parametricobject_circleprofile.Name;
			set { ifc2x3_parametricobject_circleprofile.Name = value; }
		}

		public System.String Description
		{
			get => ifc2x3_parametricobject_circleprofile.Description;
			set { ifc2x3_parametricobject_circleprofile.Description = value; }
		}

		public System.String ObjectType
		{
			get => ifc2x3_parametricobject_circleprofile.ObjectType;
			set { ifc2x3_parametricobject_circleprofile.ObjectType = value; }
		}

        

        dynamic ifc2x3_parametricobject_circleprofile;
        
        public IFC2X3_ParametricObject_CircleProfile()
        {
            this.ifc2x3_parametricobject_circleprofile =  new Tekla.Structures.Model.Collaboration.IFC2X3_ParametricObject_CircleProfile();
        }

        public IFC2X3_ParametricObject_CircleProfile(dynamic tsObject)
        {
            this.ifc2x3_parametricobject_circleprofile = tsObject;
			this.Radius = ifc2x3_parametricobject_circleprofile.Radius;
			this.Origin = new Dynamic.Tekla.Structures.Geometry3d.Point(ifc2x3_parametricobject_circleprofile.Origin);
			this.xDir = new Dynamic.Tekla.Structures.Geometry3d.Vector(ifc2x3_parametricobject_circleprofile.xDir);
			this.Extrusion = new Dynamic.Tekla.Structures.Geometry3d.Vector(ifc2x3_parametricobject_circleprofile.Extrusion);
			this.ProfileName = ifc2x3_parametricobject_circleprofile.ProfileName;
			this.Name = ifc2x3_parametricobject_circleprofile.Name;
			this.Description = ifc2x3_parametricobject_circleprofile.Description;
			this.ObjectType = ifc2x3_parametricobject_circleprofile.ObjectType;

        }


        public dynamic GetTSObject() => ifc2x3_parametricobject_circleprofile;

		public System.Boolean Equals(System.Object obj)
			 => ifc2x3_parametricobject_circleprofile.Equals(obj);

		public System.Int32 GetHashCode()
			 => ifc2x3_parametricobject_circleprofile.GetHashCode();

		public System.Type GetType()
			 => ifc2x3_parametricobject_circleprofile.GetType();

		public System.String ToString()
			 => ifc2x3_parametricobject_circleprofile.ToString();





    }

}
    
