//Generated by script in project CodeGenerator
//Copyright Dawid Dyrcz 2020 see license file

namespace Dynamic.Tekla.Structures.Model.Collaboration
{

    public sealed class IFC2X3_ParametricObject_LShapeProfile 
    {

		public System.Double Depth
		{
			get => ifc2x3_parametricobject_lshapeprofile.Depth;
			set { ifc2x3_parametricobject_lshapeprofile.Depth = value; }
		}

		public System.Double Width
		{
			get => ifc2x3_parametricobject_lshapeprofile.Width;
			set { ifc2x3_parametricobject_lshapeprofile.Width = value; }
		}

		public System.Double Thickness
		{
			get => ifc2x3_parametricobject_lshapeprofile.Thickness;
			set { ifc2x3_parametricobject_lshapeprofile.Thickness = value; }
		}

		public System.Double FilletRadius
		{
			get => ifc2x3_parametricobject_lshapeprofile.FilletRadius;
			set { ifc2x3_parametricobject_lshapeprofile.FilletRadius = value; }
		}

		public System.Double EdgeRadius
		{
			get => ifc2x3_parametricobject_lshapeprofile.EdgeRadius;
			set { ifc2x3_parametricobject_lshapeprofile.EdgeRadius = value; }
		}

		public System.Double LegSlope
		{
			get => ifc2x3_parametricobject_lshapeprofile.LegSlope;
			set { ifc2x3_parametricobject_lshapeprofile.LegSlope = value; }
		}

		public Dynamic.Tekla.Structures.Geometry3d.Point Origin
		{
			get => new Dynamic.Tekla.Structures.Geometry3d.Point(ifc2x3_parametricobject_lshapeprofile.Origin.GetTSObject());
			set { ifc2x3_parametricobject_lshapeprofile.Origin = value.GetTSObject(); }
		}

		public Dynamic.Tekla.Structures.Geometry3d.Vector xDir
		{
			get => new Dynamic.Tekla.Structures.Geometry3d.Vector(ifc2x3_parametricobject_lshapeprofile.xDir.GetTSObject());
			set { ifc2x3_parametricobject_lshapeprofile.xDir = value.GetTSObject(); }
		}

		public Dynamic.Tekla.Structures.Geometry3d.Vector Extrusion
		{
			get => new Dynamic.Tekla.Structures.Geometry3d.Vector(ifc2x3_parametricobject_lshapeprofile.Extrusion.GetTSObject());
			set { ifc2x3_parametricobject_lshapeprofile.Extrusion = value.GetTSObject(); }
		}

		public System.String ProfileName
		{
			get => ifc2x3_parametricobject_lshapeprofile.ProfileName;
			set { ifc2x3_parametricobject_lshapeprofile.ProfileName = value; }
		}

		public System.String Name
		{
			get => ifc2x3_parametricobject_lshapeprofile.Name;
			set { ifc2x3_parametricobject_lshapeprofile.Name = value; }
		}

		public System.String Description
		{
			get => ifc2x3_parametricobject_lshapeprofile.Description;
			set { ifc2x3_parametricobject_lshapeprofile.Description = value; }
		}

		public System.String ObjectType
		{
			get => ifc2x3_parametricobject_lshapeprofile.ObjectType;
			set { ifc2x3_parametricobject_lshapeprofile.ObjectType = value; }
		}

        

        dynamic ifc2x3_parametricobject_lshapeprofile;
        
        public IFC2X3_ParametricObject_LShapeProfile()
        {
            this.ifc2x3_parametricobject_lshapeprofile =  new Tekla.Structures.Model.Collaboration.IFC2X3_ParametricObject_LShapeProfile();
        }

        public IFC2X3_ParametricObject_LShapeProfile(dynamic tsObject)
        {
            this.ifc2x3_parametricobject_lshapeprofile = tsObject;
			this.Depth = ifc2x3_parametricobject_lshapeprofile.Depth;
			this.Width = ifc2x3_parametricobject_lshapeprofile.Width;
			this.Thickness = ifc2x3_parametricobject_lshapeprofile.Thickness;
			this.FilletRadius = ifc2x3_parametricobject_lshapeprofile.FilletRadius;
			this.EdgeRadius = ifc2x3_parametricobject_lshapeprofile.EdgeRadius;
			this.LegSlope = ifc2x3_parametricobject_lshapeprofile.LegSlope;
			this.Origin = new Dynamic.Tekla.Structures.Geometry3d.Point(ifc2x3_parametricobject_lshapeprofile.Origin);
			this.xDir = new Dynamic.Tekla.Structures.Geometry3d.Vector(ifc2x3_parametricobject_lshapeprofile.xDir);
			this.Extrusion = new Dynamic.Tekla.Structures.Geometry3d.Vector(ifc2x3_parametricobject_lshapeprofile.Extrusion);
			this.ProfileName = ifc2x3_parametricobject_lshapeprofile.ProfileName;
			this.Name = ifc2x3_parametricobject_lshapeprofile.Name;
			this.Description = ifc2x3_parametricobject_lshapeprofile.Description;
			this.ObjectType = ifc2x3_parametricobject_lshapeprofile.ObjectType;

        }


        public dynamic GetTSObject() => ifc2x3_parametricobject_lshapeprofile;





    }

}
    
