//Generated by script in project CodeGenerator
//Copyright Dawid Dyrcz 2020 see license file

namespace Dynamic.Tekla.Structures.Model.Collaboration
{

    public sealed class IFC2X3_ParametricObject_EllipseProfile 
    {

		public System.Double SemiAxis1
		{
			get => ifc2x3_parametricobject_ellipseprofile.SemiAxis1;
			set { ifc2x3_parametricobject_ellipseprofile.SemiAxis1 = value; }
		}

		public System.Double SemiAxis2
		{
			get => ifc2x3_parametricobject_ellipseprofile.SemiAxis2;
			set { ifc2x3_parametricobject_ellipseprofile.SemiAxis2 = value; }
		}

		public Dynamic.Tekla.Structures.Geometry3d.Point Origin
		{
			get => new Dynamic.Tekla.Structures.Geometry3d.Point(ifc2x3_parametricobject_ellipseprofile.Origin.GetTSObject());
			set { ifc2x3_parametricobject_ellipseprofile.Origin = value.GetTSObject(); }
		}

		public Dynamic.Tekla.Structures.Geometry3d.Vector xDir
		{
			get => new Dynamic.Tekla.Structures.Geometry3d.Vector(ifc2x3_parametricobject_ellipseprofile.xDir.GetTSObject());
			set { ifc2x3_parametricobject_ellipseprofile.xDir = value.GetTSObject(); }
		}

		public Dynamic.Tekla.Structures.Geometry3d.Vector Extrusion
		{
			get => new Dynamic.Tekla.Structures.Geometry3d.Vector(ifc2x3_parametricobject_ellipseprofile.Extrusion.GetTSObject());
			set { ifc2x3_parametricobject_ellipseprofile.Extrusion = value.GetTSObject(); }
		}

		public System.String ProfileName
		{
			get => ifc2x3_parametricobject_ellipseprofile.ProfileName;
			set { ifc2x3_parametricobject_ellipseprofile.ProfileName = value; }
		}

		public System.String Name
		{
			get => ifc2x3_parametricobject_ellipseprofile.Name;
			set { ifc2x3_parametricobject_ellipseprofile.Name = value; }
		}

		public System.String Description
		{
			get => ifc2x3_parametricobject_ellipseprofile.Description;
			set { ifc2x3_parametricobject_ellipseprofile.Description = value; }
		}

		public System.String ObjectType
		{
			get => ifc2x3_parametricobject_ellipseprofile.ObjectType;
			set { ifc2x3_parametricobject_ellipseprofile.ObjectType = value; }
		}

        

        dynamic ifc2x3_parametricobject_ellipseprofile;
        
        public IFC2X3_ParametricObject_EllipseProfile()
        {
            this.ifc2x3_parametricobject_ellipseprofile =  new Tekla.Structures.Model.Collaboration.IFC2X3_ParametricObject_EllipseProfile();
        }

        public IFC2X3_ParametricObject_EllipseProfile(dynamic tsObject)
        {
            this.ifc2x3_parametricobject_ellipseprofile = tsObject;
			this.SemiAxis1 = ifc2x3_parametricobject_ellipseprofile.SemiAxis1;
			this.SemiAxis2 = ifc2x3_parametricobject_ellipseprofile.SemiAxis2;
			this.Origin = new Dynamic.Tekla.Structures.Geometry3d.Point(ifc2x3_parametricobject_ellipseprofile.Origin);
			this.xDir = new Dynamic.Tekla.Structures.Geometry3d.Vector(ifc2x3_parametricobject_ellipseprofile.xDir);
			this.Extrusion = new Dynamic.Tekla.Structures.Geometry3d.Vector(ifc2x3_parametricobject_ellipseprofile.Extrusion);
			this.ProfileName = ifc2x3_parametricobject_ellipseprofile.ProfileName;
			this.Name = ifc2x3_parametricobject_ellipseprofile.Name;
			this.Description = ifc2x3_parametricobject_ellipseprofile.Description;
			this.ObjectType = ifc2x3_parametricobject_ellipseprofile.ObjectType;

        }


        public dynamic GetTSObject() => ifc2x3_parametricobject_ellipseprofile;





    }

}
    
