//Generated by script in project CodeGenerator
//Copyright Dawid Dyrcz 2020 see license file

namespace Dynamic.Tekla.Structures.Model.Collaboration
{

    public sealed class ParametricObject_CustomProfile 
    {

		public Dynamic.Tekla.Structures.Geometry3d.Point Origin
		{
			get => new Dynamic.Tekla.Structures.Geometry3d.Point(parametricobject_customprofile.Origin.GetTSObject());
			set { parametricobject_customprofile.Origin = value.GetTSObject(); }
		}

		public Dynamic.Tekla.Structures.Geometry3d.Vector xDir
		{
			get => new Dynamic.Tekla.Structures.Geometry3d.Vector(parametricobject_customprofile.xDir.GetTSObject());
			set { parametricobject_customprofile.xDir = value.GetTSObject(); }
		}

		public Dynamic.Tekla.Structures.Geometry3d.Vector Extrusion
		{
			get => new Dynamic.Tekla.Structures.Geometry3d.Vector(parametricobject_customprofile.Extrusion.GetTSObject());
			set { parametricobject_customprofile.Extrusion = value.GetTSObject(); }
		}

		public System.String ProfileName
		{
			get => parametricobject_customprofile.ProfileName;
			set { parametricobject_customprofile.ProfileName = value; }
		}

		public System.String Name
		{
			get => parametricobject_customprofile.Name;
			set { parametricobject_customprofile.Name = value; }
		}

		public System.String Description
		{
			get => parametricobject_customprofile.Description;
			set { parametricobject_customprofile.Description = value; }
		}

		public System.String ObjectType
		{
			get => parametricobject_customprofile.ObjectType;
			set { parametricobject_customprofile.ObjectType = value; }
		}

        

        dynamic parametricobject_customprofile;
        
        public ParametricObject_CustomProfile()
        {
            this.parametricobject_customprofile =  new Tekla.Structures.Model.Collaboration.ParametricObject_CustomProfile();
        }

        public ParametricObject_CustomProfile(dynamic tsObject)
        {
            this.parametricobject_customprofile = tsObject;
			this.Origin = new Dynamic.Tekla.Structures.Geometry3d.Point(parametricobject_customprofile.Origin);
			this.xDir = new Dynamic.Tekla.Structures.Geometry3d.Vector(parametricobject_customprofile.xDir);
			this.Extrusion = new Dynamic.Tekla.Structures.Geometry3d.Vector(parametricobject_customprofile.Extrusion);
			this.ProfileName = parametricobject_customprofile.ProfileName;
			this.Name = parametricobject_customprofile.Name;
			this.Description = parametricobject_customprofile.Description;
			this.ObjectType = parametricobject_customprofile.ObjectType;

        }


        public dynamic GetTSObject() => parametricobject_customprofile;

		public System.Boolean Equals(System.Object obj)
			 => parametricobject_customprofile.Equals(obj);

		public System.Int32 GetHashCode()
			 => parametricobject_customprofile.GetHashCode();

		public System.Type GetType()
			 => parametricobject_customprofile.GetType();

		public System.String ToString()
			 => parametricobject_customprofile.ToString();





    }

}
    
