//Generated by script in project CodeGenerator
//Copyright Dawid Dyrcz 2020 see license file

namespace Dynamic.Tekla.Structures.Model.Collaboration
{

    public sealed class ParametricObject_ObjectBoundingBox 
    {

		public Dynamic.Tekla.Structures.Geometry3d.Vector yDir
		{
			get => new Dynamic.Tekla.Structures.Geometry3d.Vector(parametricobject_objectboundingbox.yDir.GetTSObject());
			set { parametricobject_objectboundingbox.yDir = value.GetTSObject(); }
		}

		public Dynamic.Tekla.Structures.Geometry3d.Point Origin
		{
			get => new Dynamic.Tekla.Structures.Geometry3d.Point(parametricobject_objectboundingbox.Origin.GetTSObject());
			set { parametricobject_objectboundingbox.Origin = value.GetTSObject(); }
		}

		public Dynamic.Tekla.Structures.Geometry3d.Vector xDir
		{
			get => new Dynamic.Tekla.Structures.Geometry3d.Vector(parametricobject_objectboundingbox.xDir.GetTSObject());
			set { parametricobject_objectboundingbox.xDir = value.GetTSObject(); }
		}

		public Dynamic.Tekla.Structures.Geometry3d.Vector Extrusion
		{
			get => new Dynamic.Tekla.Structures.Geometry3d.Vector(parametricobject_objectboundingbox.Extrusion.GetTSObject());
			set { parametricobject_objectboundingbox.Extrusion = value.GetTSObject(); }
		}

		public System.String ProfileName
		{
			get => parametricobject_objectboundingbox.ProfileName;
			set { parametricobject_objectboundingbox.ProfileName = value; }
		}

		public System.String Name
		{
			get => parametricobject_objectboundingbox.Name;
			set { parametricobject_objectboundingbox.Name = value; }
		}

		public System.String Description
		{
			get => parametricobject_objectboundingbox.Description;
			set { parametricobject_objectboundingbox.Description = value; }
		}

		public System.String ObjectType
		{
			get => parametricobject_objectboundingbox.ObjectType;
			set { parametricobject_objectboundingbox.ObjectType = value; }
		}

        

        dynamic parametricobject_objectboundingbox;
        
        public ParametricObject_ObjectBoundingBox()
        {
            this.parametricobject_objectboundingbox =  TSActivator.CreateInstance("Tekla.Structures.Model.Collaboration.ParametricObject_ObjectBoundingBox");
        }

        public ParametricObject_ObjectBoundingBox(dynamic tsObject)
        {
            this.parametricobject_objectboundingbox = tsObject;
			this.yDir = new Dynamic.Tekla.Structures.Geometry3d.Vector(parametricobject_objectboundingbox.yDir);
			this.Origin = new Dynamic.Tekla.Structures.Geometry3d.Point(parametricobject_objectboundingbox.Origin);
			this.xDir = new Dynamic.Tekla.Structures.Geometry3d.Vector(parametricobject_objectboundingbox.xDir);
			this.Extrusion = new Dynamic.Tekla.Structures.Geometry3d.Vector(parametricobject_objectboundingbox.Extrusion);
			this.ProfileName = parametricobject_objectboundingbox.ProfileName;
			this.Name = parametricobject_objectboundingbox.Name;
			this.Description = parametricobject_objectboundingbox.Description;
			this.ObjectType = parametricobject_objectboundingbox.ObjectType;

        }


        public dynamic GetTSObject() => parametricobject_objectboundingbox;





    }

}
    
