//Generated by script in project CodeGenerator
//Copyright Dawid Dyrcz 2020 see license file

namespace Dynamic.Tekla.Structures.Model
{

    public sealed class RebarMesh 
    {

		public Dynamic.Tekla.Structures.Model.RebarMesh.RebarMeshTypeEnum MeshType
		{
			get => Dynamic.Tekla.Structures.Model.RebarMesh.RebarMeshTypeEnum_.FromTSObject(rebarmesh.MeshType);
			set { rebarmesh.MeshType = Dynamic.Tekla.Structures.Model.RebarMesh.RebarMeshTypeEnum_.FromTSObject(value); }
		}

		public Dynamic.Tekla.Structures.Model.RebarMesh.RebarMeshSpacingMethodEnum LongitudinalSpacingMethod
		{
			get => Dynamic.Tekla.Structures.Model.RebarMesh.RebarMeshSpacingMethodEnum_.FromTSObject(rebarmesh.LongitudinalSpacingMethod);
			set { rebarmesh.LongitudinalSpacingMethod = Dynamic.Tekla.Structures.Model.RebarMesh.RebarMeshSpacingMethodEnum_.FromTSObject(value); }
		}

		public Dynamic.Tekla.Structures.Model.Polygon Polygon
		{
			get => new Dynamic.Tekla.Structures.Model.Polygon(rebarmesh.Polygon.GetTSObject());
			set { rebarmesh.Polygon = value.GetTSObject(); }
		}

		public System.Collections.ArrayList LongitudinalDistances
		{
			get => rebarmesh.LongitudinalDistances;
			set { rebarmesh.LongitudinalDistances = value; }
		}

		public System.Collections.ArrayList CrossDistances
		{
			get => rebarmesh.CrossDistances;
			set { rebarmesh.CrossDistances = value; }
		}

		public System.Double FromPlaneOffset
		{
			get => rebarmesh.FromPlaneOffset;
			set { rebarmesh.FromPlaneOffset = value; }
		}

		public System.Double StartFromPlaneOffset
		{
			get => rebarmesh.StartFromPlaneOffset;
			set { rebarmesh.StartFromPlaneOffset = value; }
		}

		public System.Double EndFromPlaneOffset
		{
			get => rebarmesh.EndFromPlaneOffset;
			set { rebarmesh.EndFromPlaneOffset = value; }
		}

		public Dynamic.Tekla.Structures.Geometry3d.Point StartPoint
		{
			get => new Dynamic.Tekla.Structures.Geometry3d.Point(rebarmesh.StartPoint.GetTSObject());
			set { rebarmesh.StartPoint = value.GetTSObject(); }
		}

		public Dynamic.Tekla.Structures.Geometry3d.Point EndPoint
		{
			get => new Dynamic.Tekla.Structures.Geometry3d.Point(rebarmesh.EndPoint.GetTSObject());
			set { rebarmesh.EndPoint = value.GetTSObject(); }
		}

		public System.Double LeftOverhangLongitudinal
		{
			get => rebarmesh.LeftOverhangLongitudinal;
			set { rebarmesh.LeftOverhangLongitudinal = value; }
		}

		public System.Double LeftOverhangCross
		{
			get => rebarmesh.LeftOverhangCross;
			set { rebarmesh.LeftOverhangCross = value; }
		}

		public System.Double RightOverhangLongitudinal
		{
			get => rebarmesh.RightOverhangLongitudinal;
			set { rebarmesh.RightOverhangLongitudinal = value; }
		}

		public System.Double RightOverhangCross
		{
			get => rebarmesh.RightOverhangCross;
			set { rebarmesh.RightOverhangCross = value; }
		}

		public System.String LongitudinalSize
		{
			get => rebarmesh.LongitudinalSize;
			set { rebarmesh.LongitudinalSize = value; }
		}

		public System.String CrossSize
		{
			get => rebarmesh.CrossSize;
			set { rebarmesh.CrossSize = value; }
		}

		public System.Double Width
		{
			get => rebarmesh.Width;
			set { rebarmesh.Width = value; }
		}

		public System.Double Length
		{
			get => rebarmesh.Length;
			set { rebarmesh.Length = value; }
		}

		public System.Boolean CutByFatherPartCuts
		{
			get => rebarmesh.CutByFatherPartCuts;
			set { rebarmesh.CutByFatherPartCuts = value; }
		}

		public System.String CatalogName
		{
			get => rebarmesh.CatalogName;
			set { rebarmesh.CatalogName = value; }
		}

		public Dynamic.Tekla.Structures.Model.RebarMesh.RebarMeshCrossBarLocationEnum CrossBarLocation
		{
			get => Dynamic.Tekla.Structures.Model.RebarMesh.RebarMeshCrossBarLocationEnum_.FromTSObject(rebarmesh.CrossBarLocation);
			set { rebarmesh.CrossBarLocation = Dynamic.Tekla.Structures.Model.RebarMesh.RebarMeshCrossBarLocationEnum_.FromTSObject(value); }
		}

		public Dynamic.Tekla.Structures.Model.RebarHookData StartHook
		{
			get => new Dynamic.Tekla.Structures.Model.RebarHookData(rebarmesh.StartHook.GetTSObject());
			set { rebarmesh.StartHook = value.GetTSObject(); }
		}

		public Dynamic.Tekla.Structures.Model.RebarHookData EndHook
		{
			get => new Dynamic.Tekla.Structures.Model.RebarHookData(rebarmesh.EndHook.GetTSObject());
			set { rebarmesh.EndHook = value.GetTSObject(); }
		}

		public Dynamic.Tekla.Structures.Model.ModelObject Father
		{
			get => new Dynamic.Tekla.Structures.Model.ModelObject(rebarmesh.Father.GetTSObject());
			set { rebarmesh.Father = value.GetTSObject(); }
		}

		public System.String Grade
		{
			get => rebarmesh.Grade;
			set { rebarmesh.Grade = value; }
		}

		public System.String Name
		{
			get => rebarmesh.Name;
			set { rebarmesh.Name = value; }
		}

		public System.Int32 Class
		{
			get => rebarmesh.Class;
			set { rebarmesh.Class = value; }
		}

		public Dynamic.Tekla.Structures.Model.NumberingSeries NumberingSeries
		{
			get => new Dynamic.Tekla.Structures.Model.NumberingSeries(rebarmesh.NumberingSeries.GetTSObject());
			set { rebarmesh.NumberingSeries = value.GetTSObject(); }
		}

		public System.Collections.ArrayList OnPlaneOffsets
		{
			get => rebarmesh.OnPlaneOffsets;
			set { rebarmesh.OnPlaneOffsets = value; }
		}

		public Dynamic.Tekla.Structures.Model.Reinforcement.RebarOffsetTypeEnum StartPointOffsetType
		{
			get => Dynamic.Tekla.Structures.Model.Reinforcement.RebarOffsetTypeEnum_.FromTSObject(rebarmesh.StartPointOffsetType);
			set { rebarmesh.StartPointOffsetType = Dynamic.Tekla.Structures.Model.Reinforcement.RebarOffsetTypeEnum_.FromTSObject(value); }
		}

		public System.Double StartPointOffsetValue
		{
			get => rebarmesh.StartPointOffsetValue;
			set { rebarmesh.StartPointOffsetValue = value; }
		}

		public Dynamic.Tekla.Structures.Model.Reinforcement.RebarOffsetTypeEnum EndPointOffsetType
		{
			get => Dynamic.Tekla.Structures.Model.Reinforcement.RebarOffsetTypeEnum_.FromTSObject(rebarmesh.EndPointOffsetType);
			set { rebarmesh.EndPointOffsetType = Dynamic.Tekla.Structures.Model.Reinforcement.RebarOffsetTypeEnum_.FromTSObject(value); }
		}

		public System.Double EndPointOffsetValue
		{
			get => rebarmesh.EndPointOffsetValue;
			set { rebarmesh.EndPointOffsetValue = value; }
		}

		public System.Collections.ArrayList RadiusValues
		{
			get => rebarmesh.RadiusValues;
			set { rebarmesh.RadiusValues = value; }
		}

		public Dynamic.Tekla.Structures.Forming.DeformingType InputPointDeformingState
		{
			get => Dynamic.Tekla.Structures.Forming.DeformingType_.FromTSObject(rebarmesh.InputPointDeformingState);
			set { rebarmesh.InputPointDeformingState = Dynamic.Tekla.Structures.Forming.DeformingType_.FromTSObject(value); }
		}

		public System.DateTime ModificationTime
		{
			get => rebarmesh.ModificationTime;
			set { rebarmesh.ModificationTime = value; }
		}

		public System.Boolean IsUpToDate
		{
			get => rebarmesh.IsUpToDate;
			set { rebarmesh.IsUpToDate = value; }
		}

		public Dynamic.Tekla.Structures.Identifier Identifier
		{
			get => new Dynamic.Tekla.Structures.Identifier(rebarmesh.Identifier.GetTSObject());
			set { rebarmesh.Identifier = value.GetTSObject(); }
		}

        

        dynamic rebarmesh;
        
        public RebarMesh()
        {
            this.rebarmesh =  new Tekla.Structures.Model.RebarMesh();
        }

        public RebarMesh(dynamic tsObject)
        {
            this.rebarmesh = tsObject;
			this.MeshType = Dynamic.Tekla.Structures.Model.RebarMesh.RebarMeshTypeEnum_.FromTSObject(rebarmesh.MeshType);
			this.LongitudinalSpacingMethod = Dynamic.Tekla.Structures.Model.RebarMesh.RebarMeshSpacingMethodEnum_.FromTSObject(rebarmesh.LongitudinalSpacingMethod);
			this.Polygon = new Dynamic.Tekla.Structures.Model.Polygon(rebarmesh.Polygon);
			this.LongitudinalDistances = rebarmesh.LongitudinalDistances;
			this.CrossDistances = rebarmesh.CrossDistances;
			this.FromPlaneOffset = rebarmesh.FromPlaneOffset;
			this.StartFromPlaneOffset = rebarmesh.StartFromPlaneOffset;
			this.EndFromPlaneOffset = rebarmesh.EndFromPlaneOffset;
			this.StartPoint = new Dynamic.Tekla.Structures.Geometry3d.Point(rebarmesh.StartPoint);
			this.EndPoint = new Dynamic.Tekla.Structures.Geometry3d.Point(rebarmesh.EndPoint);
			this.LeftOverhangLongitudinal = rebarmesh.LeftOverhangLongitudinal;
			this.LeftOverhangCross = rebarmesh.LeftOverhangCross;
			this.RightOverhangLongitudinal = rebarmesh.RightOverhangLongitudinal;
			this.RightOverhangCross = rebarmesh.RightOverhangCross;
			this.LongitudinalSize = rebarmesh.LongitudinalSize;
			this.CrossSize = rebarmesh.CrossSize;
			this.Width = rebarmesh.Width;
			this.Length = rebarmesh.Length;
			this.CutByFatherPartCuts = rebarmesh.CutByFatherPartCuts;
			this.CatalogName = rebarmesh.CatalogName;
			this.CrossBarLocation = Dynamic.Tekla.Structures.Model.RebarMesh.RebarMeshCrossBarLocationEnum_.FromTSObject(rebarmesh.CrossBarLocation);
			this.StartHook = new Dynamic.Tekla.Structures.Model.RebarHookData(rebarmesh.StartHook);
			this.EndHook = new Dynamic.Tekla.Structures.Model.RebarHookData(rebarmesh.EndHook);
			this.Father = new Dynamic.Tekla.Structures.Model.ModelObject(rebarmesh.Father);
			this.Grade = rebarmesh.Grade;
			this.Name = rebarmesh.Name;
			this.Class = rebarmesh.Class;
			this.NumberingSeries = new Dynamic.Tekla.Structures.Model.NumberingSeries(rebarmesh.NumberingSeries);
			this.OnPlaneOffsets = rebarmesh.OnPlaneOffsets;
			this.StartPointOffsetType = Dynamic.Tekla.Structures.Model.Reinforcement.RebarOffsetTypeEnum_.FromTSObject(rebarmesh.StartPointOffsetType);
			this.StartPointOffsetValue = rebarmesh.StartPointOffsetValue;
			this.EndPointOffsetType = Dynamic.Tekla.Structures.Model.Reinforcement.RebarOffsetTypeEnum_.FromTSObject(rebarmesh.EndPointOffsetType);
			this.EndPointOffsetValue = rebarmesh.EndPointOffsetValue;
			this.RadiusValues = rebarmesh.RadiusValues;
			this.InputPointDeformingState = Dynamic.Tekla.Structures.Forming.DeformingType_.FromTSObject(rebarmesh.InputPointDeformingState);
			this.ModificationTime = rebarmesh.ModificationTime;
			this.IsUpToDate = rebarmesh.IsUpToDate;
			this.Identifier = new Dynamic.Tekla.Structures.Identifier(rebarmesh.Identifier);

        }


        public dynamic GetTSObject() => rebarmesh;

		public System.Boolean Insert()
			 => rebarmesh.Insert();

		public System.Boolean Select()
			 => rebarmesh.Select();

		public System.Boolean Modify()
			 => rebarmesh.Modify();

		public System.Boolean Delete()
			 => rebarmesh.Delete();

		public System.Collections.ArrayList GetRebarGeometries(Dynamic.Tekla.Structures.Model.Reinforcement.RebarGeometryOptionEnum options)
			 => rebarmesh.GetRebarGeometries(options.GetTSObject());

		public System.Collections.ArrayList GetRebarGeometries(System.Boolean withHooks)
			 => rebarmesh.GetRebarGeometries(withHooks);

		public System.Collections.ArrayList GetRebarGeometriesWithoutClashes(System.Boolean withHooks)
			 => rebarmesh.GetRebarGeometriesWithoutClashes(withHooks);

		public System.Boolean IsGeometryValid()
			 => rebarmesh.IsGeometryValid();

		public System.Int32 GetNumberOfRebars()
			 => rebarmesh.GetNumberOfRebars();

		public Dynamic.Tekla.Structures.Model.RebarGeometry GetSingleRebar(System.Int32 index, System.Boolean withHooks)
			 => new Dynamic.Tekla.Structures.Model.RebarGeometry(rebarmesh.GetSingleRebar(index, withHooks));

		public Dynamic.Tekla.Structures.Model.RebarGeometry GetSingleRebarWithoutClash(System.Int32 index, System.Boolean withHooks)
			 => new Dynamic.Tekla.Structures.Model.RebarGeometry(rebarmesh.GetSingleRebarWithoutClash(index, withHooks));

		public Dynamic.Tekla.Structures.Model.Solid GetSolid()
			 => new Dynamic.Tekla.Structures.Model.Solid(rebarmesh.GetSolid());

		public Dynamic.Tekla.Structures.Model.PourObject GetFatherPour()
			 => new Dynamic.Tekla.Structures.Model.PourObject(rebarmesh.GetFatherPour());

		public Dynamic.Tekla.Structures.Model.PourUnit GetFatherPourUnit()
			 => new Dynamic.Tekla.Structures.Model.PourUnit(rebarmesh.GetFatherPourUnit());

		public Dynamic.Tekla.Structures.Model.ModelObjectEnumerator GetChildren()
			 => new Dynamic.Tekla.Structures.Model.ModelObjectEnumerator(rebarmesh.GetChildren());

		public Dynamic.Tekla.Structures.Model.BaseComponent GetFatherComponent()
			 => new Dynamic.Tekla.Structures.Model.BaseComponent(rebarmesh.GetFatherComponent());

		public Dynamic.Tekla.Structures.Model.ModelObjectEnumerator GetHierarchicObjects()
			 => new Dynamic.Tekla.Structures.Model.ModelObjectEnumerator(rebarmesh.GetHierarchicObjects());

		public System.Boolean GetAllUserProperties(ref System.Collections.Hashtable values)
			 => rebarmesh.GetAllUserProperties(ref values);

		public System.Boolean GetIntegerUserProperties(ref System.Collections.Hashtable values)
			 => rebarmesh.GetIntegerUserProperties(ref values);

		public System.Boolean GetDoubleUserProperties(ref System.Collections.Hashtable values)
			 => rebarmesh.GetDoubleUserProperties(ref values);

		public System.Boolean GetStringUserProperties(ref System.Collections.Hashtable values)
			 => rebarmesh.GetStringUserProperties(ref values);

		public System.Boolean GetAllReportProperties(System.Collections.ArrayList stringNames, System.Collections.ArrayList doubleNames, System.Collections.ArrayList integerNames, ref System.Collections.Hashtable values)
			 => rebarmesh.GetAllReportProperties(stringNames, doubleNames, integerNames, ref values);

		public System.Boolean GetIntegerReportProperties(System.Collections.ArrayList names, ref System.Collections.Hashtable values)
			 => rebarmesh.GetIntegerReportProperties(names, ref values);

		public System.Boolean GetDoubleReportProperties(System.Collections.ArrayList names, ref System.Collections.Hashtable values)
			 => rebarmesh.GetDoubleReportProperties(names, ref values);

		public System.Boolean GetStringReportProperties(System.Collections.ArrayList names, ref System.Collections.Hashtable values)
			 => rebarmesh.GetStringReportProperties(names, ref values);

		public System.Boolean GetUserProperty(System.String name, ref System.String value)
			 => rebarmesh.GetUserProperty(name, ref value);

		public System.Boolean GetReportProperty(System.String name, ref System.String value)
			 => rebarmesh.GetReportProperty(name, ref value);

		public System.Boolean GetUserProperty(System.String name, ref System.Double value)
			 => rebarmesh.GetUserProperty(name, ref value);

		public System.Boolean GetReportProperty(System.String name, ref System.Double value)
			 => rebarmesh.GetReportProperty(name, ref value);

		public System.Boolean GetUserProperty(System.String name, ref System.Int32 value)
			 => rebarmesh.GetUserProperty(name, ref value);

		public System.Boolean GetReportProperty(System.String name, ref System.Int32 value)
			 => rebarmesh.GetReportProperty(name, ref value);

		public System.Boolean GetDynamicStringProperty(System.String name, ref System.String value)
			 => rebarmesh.GetDynamicStringProperty(name, ref value);

		public System.Boolean SetDynamicStringProperty(System.String name, System.String value)
			 => rebarmesh.SetDynamicStringProperty(name, value);

		public System.Boolean SetUserProperty(System.String name, System.String value)
			 => rebarmesh.SetUserProperty(name, value);

		public System.Boolean SetUserProperty(System.String name, System.Double value)
			 => rebarmesh.SetUserProperty(name, value);

		public System.Boolean SetUserProperty(System.String name, System.Int32 value)
			 => rebarmesh.SetUserProperty(name, value);

		public Dynamic.Tekla.Structures.Geometry3d.CoordinateSystem GetCoordinateSystem()
			 => new Dynamic.Tekla.Structures.Geometry3d.CoordinateSystem(rebarmesh.GetCoordinateSystem());

		public System.Boolean SetPhase(Dynamic.Tekla.Structures.Model.Phase phase)
			 => rebarmesh.SetPhase(phase.GetTSObject());

		public System.Boolean GetPhase(ref Dynamic.Tekla.Structures.Model.Phase phase)
			 => rebarmesh.GetPhase(ref phase.GetTSObject());

		public System.Boolean SetLabel(System.String label)
			 => rebarmesh.SetLabel(label);

		public System.Int32 CompareTo(System.Object obj)
			 => rebarmesh.CompareTo(obj);

		public System.Boolean Equals(Dynamic.Tekla.Structures.Model.ModelObject other)
			 => rebarmesh.Equals(other.GetTSObject());

		public System.Boolean Equals(System.Object obj)
			 => rebarmesh.Equals(obj);

		public System.Int32 GetHashCode()
			 => rebarmesh.GetHashCode();

		public System.Type GetType()
			 => rebarmesh.GetType();

		public System.String ToString()
			 => rebarmesh.ToString();




    public enum RebarMeshTypeEnum
    {
			UNKNOWN_MESH,
			RECTANGULAR_MESH,
			POLYGON_MESH,
			BENT_MESH        
    }

    public static class RebarMeshTypeEnum_
    {
        public static dynamic GetTSObject(RebarMeshTypeEnum dynEnum)
        {
            var tsType = TSActivator.CreateInstance("Tekla.Structures.Model.RebarMeshTypeEnum");

            switch (dynEnum)
            {
				case RebarMeshTypeEnum.UNKNOWN_MESH:
					return System.Enum.Parse(tsType, "UNKNOWN_MESH");
				case RebarMeshTypeEnum.RECTANGULAR_MESH:
					return System.Enum.Parse(tsType, "RECTANGULAR_MESH");
				case RebarMeshTypeEnum.POLYGON_MESH:
					return System.Enum.Parse(tsType, "POLYGON_MESH");
				case RebarMeshTypeEnum.BENT_MESH:
					return System.Enum.Parse(tsType, "BENT_MESH");

                default:
                    throw new System.NotImplementedException(dynEnum.ToString() + "- enum value is not implemented");
            }
        }
    
        public static RebarMeshTypeEnum FromTSObject(dynamic tsEnum)
        {
            string tsEnumValue = tsEnum.ToString("G", System.Globalization.CultureInfo.InvariantCulture);
            
			if (tsEnumValue.Equals("UNKNOWN_MESH", System.StringComparison.InvariantCulture))
				return RebarMeshTypeEnum.UNKNOWN_MESH;
			else if (tsEnumValue.Equals("RECTANGULAR_MESH", System.StringComparison.InvariantCulture))
				return RebarMeshTypeEnum.RECTANGULAR_MESH;
			else if (tsEnumValue.Equals("POLYGON_MESH", System.StringComparison.InvariantCulture))
				return RebarMeshTypeEnum.POLYGON_MESH;
			else if (tsEnumValue.Equals("BENT_MESH", System.StringComparison.InvariantCulture))
				return RebarMeshTypeEnum.BENT_MESH;

            else 
                throw new System.NotImplementedException(tsEnumValue + "- enum value is not implemented");
            
        }
    }


    public enum RebarMeshSpacingMethodEnum
    {
			SPACING_TYPE_UNDEFINED,
			SPACING_TYPE_SAME_DISTANCE,
			SPACING_TYPE_MULTIPLE_VARYING_DISTANCES        
    }

    public static class RebarMeshSpacingMethodEnum_
    {
        public static dynamic GetTSObject(RebarMeshSpacingMethodEnum dynEnum)
        {
            var tsType = TSActivator.CreateInstance("Tekla.Structures.Model.RebarMeshSpacingMethodEnum");

            switch (dynEnum)
            {
				case RebarMeshSpacingMethodEnum.SPACING_TYPE_UNDEFINED:
					return System.Enum.Parse(tsType, "SPACING_TYPE_UNDEFINED");
				case RebarMeshSpacingMethodEnum.SPACING_TYPE_SAME_DISTANCE:
					return System.Enum.Parse(tsType, "SPACING_TYPE_SAME_DISTANCE");
				case RebarMeshSpacingMethodEnum.SPACING_TYPE_MULTIPLE_VARYING_DISTANCES:
					return System.Enum.Parse(tsType, "SPACING_TYPE_MULTIPLE_VARYING_DISTANCES");

                default:
                    throw new System.NotImplementedException(dynEnum.ToString() + "- enum value is not implemented");
            }
        }
    
        public static RebarMeshSpacingMethodEnum FromTSObject(dynamic tsEnum)
        {
            string tsEnumValue = tsEnum.ToString("G", System.Globalization.CultureInfo.InvariantCulture);
            
			if (tsEnumValue.Equals("SPACING_TYPE_UNDEFINED", System.StringComparison.InvariantCulture))
				return RebarMeshSpacingMethodEnum.SPACING_TYPE_UNDEFINED;
			else if (tsEnumValue.Equals("SPACING_TYPE_SAME_DISTANCE", System.StringComparison.InvariantCulture))
				return RebarMeshSpacingMethodEnum.SPACING_TYPE_SAME_DISTANCE;
			else if (tsEnumValue.Equals("SPACING_TYPE_MULTIPLE_VARYING_DISTANCES", System.StringComparison.InvariantCulture))
				return RebarMeshSpacingMethodEnum.SPACING_TYPE_MULTIPLE_VARYING_DISTANCES;

            else 
                throw new System.NotImplementedException(tsEnumValue + "- enum value is not implemented");
            
        }
    }


    public enum RebarMeshCrossBarLocationEnum
    {
			LOCATION_TYPE_ABOVE,
			LOCATION_TYPE_BELOW,
			LOCATION_TYPE_UNDEFINED        
    }

    public static class RebarMeshCrossBarLocationEnum_
    {
        public static dynamic GetTSObject(RebarMeshCrossBarLocationEnum dynEnum)
        {
            var tsType = TSActivator.CreateInstance("Tekla.Structures.Model.RebarMeshCrossBarLocationEnum");

            switch (dynEnum)
            {
				case RebarMeshCrossBarLocationEnum.LOCATION_TYPE_ABOVE:
					return System.Enum.Parse(tsType, "LOCATION_TYPE_ABOVE");
				case RebarMeshCrossBarLocationEnum.LOCATION_TYPE_BELOW:
					return System.Enum.Parse(tsType, "LOCATION_TYPE_BELOW");
				case RebarMeshCrossBarLocationEnum.LOCATION_TYPE_UNDEFINED:
					return System.Enum.Parse(tsType, "LOCATION_TYPE_UNDEFINED");

                default:
                    throw new System.NotImplementedException(dynEnum.ToString() + "- enum value is not implemented");
            }
        }
    
        public static RebarMeshCrossBarLocationEnum FromTSObject(dynamic tsEnum)
        {
            string tsEnumValue = tsEnum.ToString("G", System.Globalization.CultureInfo.InvariantCulture);
            
			if (tsEnumValue.Equals("LOCATION_TYPE_ABOVE", System.StringComparison.InvariantCulture))
				return RebarMeshCrossBarLocationEnum.LOCATION_TYPE_ABOVE;
			else if (tsEnumValue.Equals("LOCATION_TYPE_BELOW", System.StringComparison.InvariantCulture))
				return RebarMeshCrossBarLocationEnum.LOCATION_TYPE_BELOW;
			else if (tsEnumValue.Equals("LOCATION_TYPE_UNDEFINED", System.StringComparison.InvariantCulture))
				return RebarMeshCrossBarLocationEnum.LOCATION_TYPE_UNDEFINED;

            else 
                throw new System.NotImplementedException(tsEnumValue + "- enum value is not implemented");
            
        }
    }



    }

}
    
