
//Generated by script in project CodeGenerator
//Copyright Dawid Dyrcz 2020 see license file



namespace Dynamic.Tekla.Structures.Model
{
    public sealed class SpiralBeam 
    {

		public Dynamic.Tekla.Structures.Geometry3d.Point StartPoint {get; set; }
		public Dynamic.Tekla.Structures.Geometry3d.Point RotationAxisBasePoint {get; set; }
		public Dynamic.Tekla.Structures.Geometry3d.Point RotationAxisUpPoint {get; set; }
		public System.Double TotalRise {get; set; }
		public System.Double RotationAngle {get; set; }
		public System.Double TwistAngleStart {get; set; }
		public System.Double TwistAngleEnd {get; set; }
		public Dynamic.Tekla.Structures.Geometry3d.Point RotationCenterPoint {get; set; }
		public Dynamic.Tekla.Structures.Geometry3d.Vector RotationAxisDirection {get; set; }
		public Dynamic.Tekla.Structures.Geometry3d.Point EndPoint {get; set; }
		public Dynamic.Tekla.Structures.Model.Profile Profile {get; set; }
		public Dynamic.Tekla.Structures.Model.Material Material {get; set; }
		public Dynamic.Tekla.Structures.Model.DeformingData DeformingData {get; set; }
		public Dynamic.Tekla.Structures.Model.NumberingSeries PartNumber {get; set; }
		public Dynamic.Tekla.Structures.Model.NumberingSeries AssemblyNumber {get; set; }
		public System.String Name {get; set; }
		public System.String Class {get; set; }
		public System.String Finish {get; set; }
		public Dynamic.Tekla.Structures.Model.CastUnitTypeEnum CastUnitType {get; set; }
		public System.Int32 PourPhase {get; set; }
		public Dynamic.Tekla.Structures.Model.Position Position {get; set; }
		public System.Nullable<System.DateTime> ModificationTime {get; set; }
		public System.Boolean IsUpToDate {get; set; }
		public Dynamic.Tekla.Structures.Identifier Identifier {get; set; }
        

        dynamic spiralbeam;
        
        public SpiralBeam()
        {
            this.spiralbeam =  new Tekla.Structures.Model.SpiralBeam();
        }

        public SpiralBeam(dynamic tsObject)
        {
            this.spiralbeam = tsObject;
			this.StartPoint = new Dynamic.Tekla.Structures.Geometry3d.Point(tsObject);
			this.RotationAxisBasePoint = new Dynamic.Tekla.Structures.Geometry3d.Point(tsObject);
			this.RotationAxisUpPoint = new Dynamic.Tekla.Structures.Geometry3d.Point(tsObject);
			this.TotalRise = tsObject.TotalRise;
			this.RotationAngle = tsObject.RotationAngle;
			this.TwistAngleStart = tsObject.TwistAngleStart;
			this.TwistAngleEnd = tsObject.TwistAngleEnd;
			this.RotationCenterPoint = new Dynamic.Tekla.Structures.Geometry3d.Point(tsObject);
			this.RotationAxisDirection = new Dynamic.Tekla.Structures.Geometry3d.Vector(tsObject);
			this.EndPoint = new Dynamic.Tekla.Structures.Geometry3d.Point(tsObject);
			this.Profile = new Dynamic.Tekla.Structures.Model.Profile(tsObject);
			this.Material = new Dynamic.Tekla.Structures.Model.Material(tsObject);
			this.DeformingData = new Dynamic.Tekla.Structures.Model.DeformingData(tsObject);
			this.PartNumber = new Dynamic.Tekla.Structures.Model.NumberingSeries(tsObject);
			this.AssemblyNumber = new Dynamic.Tekla.Structures.Model.NumberingSeries(tsObject);
			this.Name = tsObject.Name;
			this.Class = tsObject.Class;
			this.Finish = tsObject.Finish;
			this.CastUnitType = new Dynamic.Tekla.Structures.Model.CastUnitTypeEnum(tsObject);
			this.PourPhase = tsObject.PourPhase;
			this.Position = new Dynamic.Tekla.Structures.Model.Position(tsObject);
			this.ModificationTime = tsObject.ModificationTime;
			this.IsUpToDate = tsObject.IsUpToDate;
			this.Identifier = new Dynamic.Tekla.Structures.Identifier(tsObject);

        }


		public void Insert() => spiralbeam.Insert();
		public void Select() => spiralbeam.Select();
		public void Delete() => spiralbeam.Delete();
		public void Modify() => spiralbeam.Modify();
		public void GetSolid() => spiralbeam.GetSolid();
		public void GetSolid() => spiralbeam.GetSolid();
		public void GetSolid() => spiralbeam.GetSolid();
		public void GetAssembly() => spiralbeam.GetAssembly();
		public void GetPartMark() => spiralbeam.GetPartMark();
		public void GetCenterLine() => spiralbeam.GetCenterLine();
		public void GetReferenceLine() => spiralbeam.GetReferenceLine();
		public void GetComponents() => spiralbeam.GetComponents();
		public void GetBooleans() => spiralbeam.GetBooleans();
		public void GetBolts() => spiralbeam.GetBolts();
		public void GetWelds() => spiralbeam.GetWelds();
		public void GetReinforcements() => spiralbeam.GetReinforcements();
		public void GetSurfaceTreatments() => spiralbeam.GetSurfaceTreatments();
		public void GetSurfaceObjects() => spiralbeam.GetSurfaceObjects();
		public void GetPours() => spiralbeam.GetPours();
		public void CompareTo() => spiralbeam.CompareTo();
		public void GetDSTVCoordinateSystem() => spiralbeam.GetDSTVCoordinateSystem();
		public void GetChildren() => spiralbeam.GetChildren();
		public void GetFatherComponent() => spiralbeam.GetFatherComponent();
		public void GetHierarchicObjects() => spiralbeam.GetHierarchicObjects();
		public void GetAllUserProperties() => spiralbeam.GetAllUserProperties();
		public void GetIntegerUserProperties() => spiralbeam.GetIntegerUserProperties();
		public void GetDoubleUserProperties() => spiralbeam.GetDoubleUserProperties();
		public void GetStringUserProperties() => spiralbeam.GetStringUserProperties();
		public void GetAllReportProperties() => spiralbeam.GetAllReportProperties();
		public void GetIntegerReportProperties() => spiralbeam.GetIntegerReportProperties();
		public void GetDoubleReportProperties() => spiralbeam.GetDoubleReportProperties();
		public void GetStringReportProperties() => spiralbeam.GetStringReportProperties();
		public void GetUserProperty() => spiralbeam.GetUserProperty();
		public void GetReportProperty() => spiralbeam.GetReportProperty();
		public void GetUserProperty() => spiralbeam.GetUserProperty();
		public void GetReportProperty() => spiralbeam.GetReportProperty();
		public void GetUserProperty() => spiralbeam.GetUserProperty();
		public void GetReportProperty() => spiralbeam.GetReportProperty();
		public void GetDynamicStringProperty() => spiralbeam.GetDynamicStringProperty();
		public void SetDynamicStringProperty() => spiralbeam.SetDynamicStringProperty();
		public void SetUserProperty() => spiralbeam.SetUserProperty();
		public void SetUserProperty() => spiralbeam.SetUserProperty();
		public void SetUserProperty() => spiralbeam.SetUserProperty();
		public void GetCoordinateSystem() => spiralbeam.GetCoordinateSystem();
		public void SetPhase() => spiralbeam.SetPhase();
		public void GetPhase() => spiralbeam.GetPhase();
		public void SetLabel() => spiralbeam.SetLabel();
		public void CompareTo() => spiralbeam.CompareTo();
		public void Equals() => spiralbeam.Equals();
		public void Equals() => spiralbeam.Equals();
		public void GetHashCode() => spiralbeam.GetHashCode();
		public void GetType() => spiralbeam.GetType();
		public void ToString() => spiralbeam.ToString();


    }
}

            